In [1]:
# (I.) Linear Regression

# (1.) Loading raw data

import numpy as np 
import pandas as pd 

df = pd.read_csv("ecommerce_customer.csv")
print(df)

       Order_ID Customer_ID  Order_Date  Customer_Age Customer_Segment  \
0     ORD100994       C1229  2025-06-07          44.0       Occasional
1     ORD101072       C1627  2025-03-18          51.0       Occasional
2     ORD100995       C1410  2025-07-13           NaN       Occasional
3     ORD100731       C1578  2025-09-24          38.0          Regular
4     ORD102954       C1524  2025-06-09          39.0          Premium
...         ...         ...         ...           ...              ...
3050  ORD101148       C1685  2025-10-08          47.0          Premium
3051  ORD102155       C1641  2025-09-15          27.0          Regular
3052  ORD101767       C1457  2025-07-04          35.0          Premium
3053  ORD101123       C1789  2025-04-09          39.0       Occasional
3054  ORD101347       C1040  2025-11-09          24.0          Regular

           City   Region         Category Product_Name Sales_Channel  ...  \
0         Delhi  Central           Sports        Shoes        Online  ...
1         Kochi     West  Home Appliances        Shoes        Online  ...
2     Hyderabad     West      Electronics       Laptop        Online  ...
3     Bengaluru    North          Fashion        Shoes    Mobile App  ...
4       Kolkata    South      Electronics     Skincare   Marketplace  ...
...         ...      ...              ...          ...           ...  ...
3050      Delhi     East          Grocery        Novel    Mobile App  ...
3051  Bengaluru    North  Home Appliances        Novel        Online  ...
3052  Bengaluru     East           Sports        Shirt         Store  ...
3053      Kochi     West           Sports        Shoes        Online  ...
3054      Kochi  Central  Home Appliances       Laptop   Marketplace  ...

     Website_Session_Minutes Items_Viewed  Previous_Orders  \
0                       16.4           10               10
1                       23.2            9                3
2                        9.1           10                6
3                       22.7            4                4
4                        6.6            8                8
...                      ...          ...              ...
3050                    11.5            9                8
3051                    11.0           13                5
3052                     9.5            6                4
3053                    32.4            7                6
3054                     7.3           13                6

      Customer_Satisfaction  Gross_Amount  Discount_Amount  Net_Sales  \
0                       1.8        723.34             0.00     723.34
1                       5.0           NaN              NaN        NaN
2                       3.0        739.05           105.68     633.37
3                       3.6      28004.44          1473.03   26531.41
4                       2.5       9841.78          1842.38    7999.40
...                     ...           ...              ...        ...
3050                    4.4       1111.95           313.24     798.71
3051                    5.0        329.51            31.67     297.84
3052                    3.1      20073.84          3894.32   16179.52
3053                    3.4        274.47            44.74     229.73
3054                    3.1       5554.28           525.99    5028.29

      Estimated_Cost   Profit Profit_Margin_Pct
0             634.67    88.67             12.26
1                NaN      NaN               NaN
2             370.35   263.02             41.53
3           17911.62  8619.79             32.49
4            6214.63  1784.77             22.31
...              ...      ...               ...
3050          646.78   151.93             19.02
3051          252.38    45.46             15.26
3052        13306.36  2873.16             17.76
3053          163.04    66.69             29.03
3054         2927.82  2100.47             41.77

[3055 rows x 32 columns]

In [2]:
# (2.) Data Understanding

df.columns

Index(['Order_ID', 'Customer_ID', 'Order_Date', 'Customer_Age',
       'Customer_Segment', 'City', 'Region', 'Category', 'Product_Name',
       'Sales_Channel', 'Payment_Method', 'Device', 'Quantity', 'Unit_Price',
       'Discount_Pct', 'Shipping_Days', 'Customer_Rating', 'Delivery_Rating',
       'Return_Status', 'Order_Status', 'Marketing_Source',
       'Customer_Loyalty_Points', 'Website_Session_Minutes', 'Items_Viewed',
       'Previous_Orders', 'Customer_Satisfaction', 'Gross_Amount',
       'Discount_Amount', 'Net_Sales', 'Estimated_Cost', 'Profit',
       'Profit_Margin_Pct'],
      dtype='str')

In [3]:
df.head()

,Order_ID,Customer_ID,Order_Date,Customer_Age,Customer_Segment,City,Region,Category,Product_Name,Sales_Channel,...,Website_Session_Minutes,Items_Viewed,Previous_Orders,Customer_Satisfaction,Gross_Amount,Discount_Amount,Net_Sales,Estimated_Cost,Profit,Profit_Margin_Pct
0,ORD100994,C1229,2025-06-07,44.0,Occasional,Delhi,Central,Sports,Shoes,Online,...,16.4,10,10,1.8,723.34,0.00,723.34,634.67,88.67,12.26
1,ORD101072,C1627,2025-03-18,51.0,Occasional,Kochi,West,Home Appliances,Shoes,Online,...,23.2,9,3,5.0,NaN,NaN,NaN,NaN,NaN,NaN
2,ORD100995,C1410,2025-07-13,NaN,Occasional,Hyderabad,West,Electronics,Laptop,Online,...,9.1,10,6,3.0,739.05,105.68,633.37,370.35,263.02,41.53
3,ORD100731,C1578,2025-09-24,38.0,Regular,Bengaluru,North,Fashion,Shoes,Mobile App,...,22.7,4,4,3.6,28004.44,1473.03,26531.41,17911.62,8619.79,32.49
4,ORD102954,C1524,2025-06-09,39.0,Premium,Kolkata,South,Electronics,Skincare,Marketplace,...,6.6,8,8,2.5,9841.78,1842.38,7999.40,6214.63,1784.77,22.31

In [4]:
df.shape

(3055, 32)

In [5]:
df.dtypes

Order_ID                       str
Customer_ID                    str
Order_Date                     str
Customer_Age               float64
Customer_Segment               str
City                           str
Region                         str
Category                       str
Product_Name                   str
Sales_Channel                  str
Payment_Method                 str
Device                         str
Quantity                     int64
Unit_Price                 float64
Discount_Pct               float64
Shipping_Days              float64
Customer_Rating            float64
Delivery_Rating            float64
Return_Status                  str
Order_Status                   str
Marketing_Source               str
Customer_Loyalty_Points    float64
Website_Session_Minutes    float64
Items_Viewed                 int64
Previous_Orders              int64
Customer_Satisfaction      float64
Gross_Amount               float64
Discount_Amount            float64
Net_Sales                  float64
Estimated_Cost             float64
Profit                     float64
Profit_Margin_Pct          float64
dtype: object

In [6]:
df.isnull().sum()

Order_ID                     0
Customer_ID                  0
Order_Date                   0
Customer_Age               123
Customer_Segment             0
City                        76
Region                       0
Category                     0
Product_Name                 0
Sales_Channel                0
Payment_Method              77
Device                       0
Quantity                     0
Unit_Price                  93
Discount_Pct               153
Shipping_Days              107
Customer_Rating            215
Delivery_Rating              0
Return_Status                0
Order_Status                 0
Marketing_Source             0
Customer_Loyalty_Points    125
Website_Session_Minutes     76
Items_Viewed                 0
Previous_Orders              0
Customer_Satisfaction      154
Gross_Amount                93
Discount_Amount            245
Net_Sales                  245
Estimated_Cost             245
Profit                     245
Profit_Margin_Pct          246
dtype: int64

In [7]:
df["Order_ID"].duplicated().value_counts()

Order_ID
False    3000
True       55
Name: count, dtype: int64

In [8]:
# (2.) Remove duplicate ID's

df.drop_duplicates(subset = ["Order_ID"], keep = "first", inplace = True) 

df["Order_ID"].duplicated().value_counts()

Order_ID
False    3000
Name: count, dtype: int64

In [9]:
df.select_dtypes(include = "number").columns

Index(['Customer_Age', 'Quantity', 'Unit_Price', 'Discount_Pct',
       'Shipping_Days', 'Customer_Rating', 'Delivery_Rating',
       'Customer_Loyalty_Points', 'Website_Session_Minutes', 'Items_Viewed',
       'Previous_Orders', 'Customer_Satisfaction', 'Gross_Amount',
       'Discount_Amount', 'Net_Sales', 'Estimated_Cost', 'Profit',
       'Profit_Margin_Pct'],
      dtype='str')

In [10]:
df.select_dtypes(include = ["category","object"]).columns

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_5504\1685213237.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include = ["category","object"]).columns

Index(['Order_ID', 'Customer_ID', 'Order_Date', 'Customer_Segment', 'City',
       'Region', 'Category', 'Product_Name', 'Sales_Channel', 'Payment_Method',
       'Device', 'Return_Status', 'Order_Status', 'Marketing_Source'],
      dtype='str')

In [11]:
df.info()

<class 'pandas.DataFrame'>
Index: 3000 entries, 0 to 3054
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Order_ID                 3000 non-null   str
 1   Customer_ID              3000 non-null   str
 2   Order_Date               3000 non-null   str
 3   Customer_Age             2880 non-null   float64
 4   Customer_Segment         3000 non-null   str
 5   City                     2925 non-null   str
 6   Region                   3000 non-null   str
 7   Category                 3000 non-null   str
 8   Product_Name             3000 non-null   str
 9   Sales_Channel            3000 non-null   str
 10  Payment_Method           2925 non-null   str
 11  Device                   3000 non-null   str
 12  Quantity                 3000 non-null   int64
 13  Unit_Price               2910 non-null   float64
 14  Discount_Pct             2850 non-null   float64
 15  Shipping_Days            2895 non-null   float64
 16  Customer_Rating          2791 non-null   float64
 17  Delivery_Rating          3000 non-null   float64
 18  Return_Status            3000 non-null   str
 19  Order_Status             3000 non-null   str
 20  Marketing_Source         3000 non-null   str
 21  Customer_Loyalty_Points  2880 non-null   float64
 22  Website_Session_Minutes  2925 non-null   float64
 23  Items_Viewed             3000 non-null   int64
 24  Previous_Orders          3000 non-null   int64
 25  Customer_Satisfaction    2850 non-null   float64
 26  Gross_Amount             2910 non-null   float64
 27  Discount_Amount          2761 non-null   float64
 28  Net_Sales                2761 non-null   float64
 29  Estimated_Cost           2761 non-null   float64
 30  Profit                   2761 non-null   float64
 31  Profit_Margin_Pct        2760 non-null   float64
dtypes: float64(15), int64(3), str(14)
memory usage: 1.0 MB

In [12]:
df.describe(include="object")

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_5504\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,Order_ID,Customer_ID,Order_Date,Customer_Segment,City,Region,Category,Product_Name,Sales_Channel,Payment_Method,Device,Return_Status,Order_Status,Marketing_Source
count,3000,3000,3000,3000,2925,3000,3000,3000,3000,2925,3000,3000,3000,3000
unique,3000,776,365,4,20,5,16,10,4,11,4,2,5,5
top,ORD100994,C1744,2025-12-08,Regular,Chennai,East,Home Appliances,Novel,Online,UPI,Desktop,No,Delivered,Email
freq,1,10,20,1459,305,623,420,334,857,533,795,2594,2164,632

In [13]:
# (3.) Remove rows where the target variable Net_Sales is missing
df = df.dropna(subset=["Net_Sales"]).copy()

print("Missing Net_Sales:", df["Net_Sales"].isna().sum())
print("Dataset shape:", df.shape)

Missing Net_Sales: 0
Dataset shape: (2761, 32)

In [14]:
# (4.) Extract X and y 

y = df["Net_Sales"]           # Dependent variable
y.head()

0      723.34
2      633.37
3    26531.41
4     7999.40
5      645.34
Name: Net_Sales, dtype: float64

In [15]:
numerical_features = [
    "Customer_Age",
    "Quantity",
    "Unit_Price",
    "Discount_Pct",
    "Shipping_Days",
    "Customer_Loyalty_Points",
    "Website_Session_Minutes",
    "Items_Viewed",
    "Previous_Orders"
]

correlation_with_sales = (
    df[numerical_features + ["Net_Sales"]]
    .corr()["Net_Sales"]
    .sort_values(ascending=False)
)

print(correlation_with_sales)

Net_Sales                  1.000000
Unit_Price                 0.858965
Quantity                   0.329986
Items_Viewed               0.019274
Website_Session_Minutes    0.005339
Customer_Age               0.000883
Customer_Loyalty_Points   -0.006212
Previous_Orders           -0.016398
Shipping_Days             -0.026026
Discount_Pct              -0.073881
Name: Net_Sales, dtype: float64

In [16]:
categorical_features = [
    "Customer_Segment",
    "City",
    "Region",
    "Category",
    "Product_Name",
    "Sales_Channel",
    "Payment_Method",
    "Device",
    "Marketing_Source"
]

for column in categorical_features:
    df[column] = df[column].str.strip().str.title()

In [17]:
category_sales = (
    df.groupby("Category")["Net_Sales"]
      .agg(["count", "mean", "median"])
      .sort_values("mean", ascending=False)
)

print(category_sales)

                 count         mean    median
Category
Fashion            333  5321.600360  2385.530
Grocery            346  4681.532861  2560.100
Sports             360  4651.457194  2257.575
Furniture          324  4485.374074  2257.100
Books              314  4334.982389  2158.880
Beauty             335  4176.755672  2479.330
Home Appliances    398  3947.511960  2206.830
Electronics        351  3886.848575  2087.730

In [18]:
feature_columns = [
    "Customer_Age",
    "Customer_Segment",
    "City",
    "Region",
    "Category",
    "Product_Name",
    "Sales_Channel",
    "Payment_Method",
    "Device",
    "Quantity",
    "Unit_Price",
    "Discount_Pct",
    "Shipping_Days",
    "Marketing_Source",
    "Customer_Loyalty_Points",
    "Website_Session_Minutes",
    "Items_Viewed",
    "Previous_Orders"
]

X = df[feature_columns] 
X.head()

,Customer_Age,Customer_Segment,City,Region,Category,Product_Name,Sales_Channel,Payment_Method,Device,Quantity,Unit_Price,Discount_Pct,Shipping_Days,Marketing_Source,Customer_Loyalty_Points,Website_Session_Minutes,Items_Viewed,Previous_Orders
0,44.0,Occasional,Delhi,Central,Sports,Shoes,Online,Debit Card,Laptop,2,361.67,0.00,6.0,Social Media,1062.0,16.4,10,10
2,NaN,Occasional,Hyderabad,West,Electronics,Laptop,Online,Net Banking,Laptop,1,739.05,14.30,7.0,Referral,0.0,9.1,10,6
3,38.0,Regular,Bengaluru,North,Fashion,Shoes,Mobile App,Upi,Laptop,4,7001.11,5.26,4.0,Social Media,1388.0,22.7,4,4
4,39.0,Premium,Kolkata,South,Electronics,Skincare,Marketplace,Cash,Desktop,2,4920.89,18.72,4.0,Social Media,1132.0,6.6,8,8
5,43.0,Regular,Coimbatore,East,Fashion,Headphones,Mobile App,Upi,Desktop,1,704.06,8.34,6.0,Social Media,588.0,27.7,9,6

In [19]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (2761, 18)
y shape: (2761,)

In [20]:
# 5.) Train - test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    train_size=0.80,
    random_state=34
)

print("X_train shape:", X_train.shape)
print("X_test shape :", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape :", y_test.shape)

X_train shape: (2208, 18)
X_test shape : (553, 18)
y_train shape: (2208,)
y_test shape : (553,)

In [21]:
# (6.) Handling missing values in both training and testing data
print("Missing values in X_train:")
print(X_train.isna().sum())

print("\nMissing values in X_test:")
print(X_test.isna().sum())

Missing values in X_train:
Customer_Age               85
Customer_Segment            0
City                       54
Region                      0
Category                    0
Product_Name                0
Sales_Channel               0
Payment_Method             49
Device                      0
Quantity                    0
Unit_Price                  0
Discount_Pct                0
Shipping_Days              83
Marketing_Source            0
Customer_Loyalty_Points    88
Website_Session_Minutes    61
Items_Viewed                0
Previous_Orders             0
dtype: int64

Missing values in X_test:
Customer_Age               29
Customer_Segment            0
City                       17
Region                      0
Category                    0
Product_Name                0
Sales_Channel               0
Payment_Method             17
Device                      0
Quantity                    0
Unit_Price                  0
Discount_Pct                0
Shipping_Days              16
Marketing_Source            0
Customer_Loyalty_Points    23
Website_Session_Minutes    11
Items_Viewed                0
Previous_Orders             0
dtype: int64

In [22]:
# Handling null values in Numerical columns 

numerical_columns = X_train.select_dtypes(include="number").columns

for column in numerical_columns:
    median_value = X_train[column].median()
    
    X_train[column] = X_train[column].fillna(median_value)
    X_test[column] = X_test[column].fillna(median_value)

In [23]:
print("X_train numerical missing values:")
print(X_train[numerical_columns].isna().sum())

print("\nX_test numerical missing values:")
print(X_test[numerical_columns].isna().sum())

X_train numerical missing values:
Customer_Age               0
Quantity                   0
Unit_Price                 0
Discount_Pct               0
Shipping_Days              0
Customer_Loyalty_Points    0
Website_Session_Minutes    0
Items_Viewed               0
Previous_Orders            0
dtype: int64

X_test numerical missing values:
Customer_Age               0
Quantity                   0
Unit_Price                 0
Discount_Pct               0
Shipping_Days              0
Customer_Loyalty_Points    0
Website_Session_Minutes    0
Items_Viewed               0
Previous_Orders            0
dtype: int64

In [24]:
# Handling null values for categorical columns for training and testing rows 

categorical_columns = X_train.select_dtypes(include="object").columns

for column in categorical_columns:
    mode_value = X_train[column].mode()[0]
    
    X_train[column] = X_train[column].fillna(mode_value)
    X_test[column] = X_test[column].fillna(mode_value)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_5504\2262376738.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = X_train.select_dtypes(include="object").columns

In [25]:
print("X_train categorical missing values:")
print(X_train[categorical_columns].isna().sum())

print("\nX_test categorical missing values:")
print(X_test[categorical_columns].isna().sum())

X_train categorical missing values:
Customer_Segment    0
City                0
Region              0
Category            0
Product_Name        0
Sales_Channel       0
Payment_Method      0
Device              0
Marketing_Source    0
dtype: int64

X_test categorical missing values:
Customer_Segment    0
City                0
Region              0
Category            0
Product_Name        0
Sales_Channel       0
Payment_Method      0
Device              0
Marketing_Source    0
dtype: int64

In [26]:
for column in categorical_columns:
    X_train[column] = X_train[column].str.strip().str.title()
    X_test[column] = X_test[column].str.strip().str.title()

print("Categorical values cleaned.")

Categorical values cleaned.

In [27]:
# Outliers detection

import pandas as pd

numerical_columns = X.select_dtypes(include="number").columns.tolist()

outlier_summary = []

for col in numerical_columns:
    Q1 = X[col].quantile(0.25)
    Q3 = X[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = X[(X[col] < lower_bound) | (X[col] > upper_bound)][col]

    outlier_summary.append({
        "Feature": col,
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "Lower Bound": lower_bound,
        "Upper Bound": upper_bound,
        "Outlier Count": len(outliers),
        "Outlier %": round((len(outliers) / len(X)) * 100, 2)
    })

outlier_summary = pd.DataFrame(outlier_summary)

display(outlier_summary.sort_values(
    "Outlier Count",
    ascending=False
))

,Feature,Q1,Q3,IQR,Lower Bound,Upper Bound,Outlier Count,Outlier %
2,Unit_Price,476.04,1862.2,1386.16,-1603.200,3941.440,218,7.90
6,Website_Session_Minutes,7.90,19.4,11.50,-9.350,36.650,76,2.75
8,Previous_Orders,3.00,6.0,3.00,-1.500,10.500,46,1.67
0,Customer_Age,28.00,42.0,14.00,7.000,63.000,38,1.38
1,Quantity,2.00,4.0,2.00,-1.000,7.000,36,1.30
3,Discount_Pct,8.19,21.6,13.41,-11.925,41.715,17,0.62
5,Customer_Loyalty_Points,353.25,1300.5,947.25,-1067.625,2721.375,10,0.36
4,Shipping_Days,3.00,6.0,3.00,-1.500,10.500,9,0.33
7,Items_Viewed,5.00,9.0,4.00,-1.000,15.000,8,0.29

In [28]:
# Replace IQR-based outliers with the median

X_outlier_handled = X.copy()

for col in numerical_columns:
    Q1 = X_outlier_handled[col].quantile(0.25)
    Q3 = X_outlier_handled[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    median_value = X_outlier_handled[col].median()

    # Replace outliers with median
    X_outlier_handled.loc[
        (X_outlier_handled[col] < lower_bound) |
        (X_outlier_handled[col] > upper_bound),
        col
    ] = median_value

print("Outlier replacement completed.")

Outlier replacement completed.

In [29]:
# (8. and 9.) Feature scaling and encoding

from sklearn.preprocessing import StandardScaler, OneHotEncoder

scaler = StandardScaler()

encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

# Scale numerical features
X_train_num = scaler.fit_transform(X_train[numerical_columns])
X_test_num = scaler.transform(X_test[numerical_columns])

# Encode categorical features
X_train_cat = encoder.fit_transform(X_train[categorical_columns])
X_test_cat = encoder.transform(X_test[categorical_columns])

print("Numerical training shape:", X_train_num.shape)
print("Categorical training shape:", X_train_cat.shape)

print("Numerical test shape:", X_test_num.shape)
print("Categorical test shape:", X_test_cat.shape)

Numerical training shape: (2208, 9)
Categorical training shape: (2208, 56)
Numerical test shape: (553, 9)
Categorical test shape: (553, 56)

In [30]:
# (10.) Combine the processed features

import numpy as np

X_train_processed = np.hstack([
    X_train_num,
    X_train_cat
])

X_test_processed = np.hstack([
    X_test_num,
    X_test_cat
])

print("X_train_processed:", X_train_processed.shape)
print("X_test_processed :", X_test_processed.shape)

X_train_processed: (2208, 65)
X_test_processed : (553, 65)

In [31]:
print("NaN values in X_train_processed:", np.isnan(X_train_processed).sum())
print("NaN values in X_test_processed :", np.isnan(X_test_processed).sum())

NaN values in X_train_processed: 0
NaN values in X_test_processed : 0

In [32]:
# (11.) Training data with linear regression algorithm 

from sklearn.linear_model import LinearRegression

linear_model = LinearRegression()

linear_model.fit(
    X_train_processed,
    y_train
)

print("Linear Regression model trained successfully.")

Linear Regression model trained successfully.

In [33]:
y_pred = linear_model.predict(X_test_processed)

print("Predictions generated successfully.")
print(y_pred[:10])

Predictions generated successfully.
[  885.68420414  3428.94100032 13507.23252506  7374.57053677
  6068.78726821  8152.31508911  5821.56893166  1331.71023746
  1312.56049715  3491.14720931]

In [34]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R²  :", r2)

MAE : 1474.1967865909612
MSE : 8849624.899609964
RMSE: 2974.8319111522865
R²  : 0.8180316569469919

In [35]:
# (II.) Logistic Regression

# Finding threshold value 

median_sales = df["Net_Sales"].median() 

df["Sales_Category"] = np.where(df["Net_Sales"] >= median_sales, "High sales", "Low sales") 

print(df[["Net_Sales","Sales_Category"]].sample(5)) 
print("-------------------------------------------")
print(df["Sales_Category"].value_counts())

      Net_Sales Sales_Category
2008     332.05      Low sales
2666    2148.89      Low sales
1524    8349.93     High sales
2143    2206.63      Low sales
2171    2562.23     High sales
-------------------------------------------
Sales_Category
High sales    1381
Low sales     1380
Name: count, dtype: int64

In [36]:
feature_columns = [
    "Customer_Age",
    "Customer_Segment",
    "City",
    "Region",
    "Category",
    "Product_Name",
    "Sales_Channel",
    "Payment_Method",
    "Device",
    "Quantity",
    "Unit_Price",
    "Discount_Pct",
    "Shipping_Days",
    "Marketing_Source",
    "Customer_Loyalty_Points",
    "Website_Session_Minutes",
    "Items_Viewed",
    "Previous_Orders"
]

X = df[feature_columns]
y = df["Sales_Category"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (2761, 18)
y shape: (2761,)

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    train_size=0.80,
    random_state=34,
    stratify=y                        # It maintains the same Low sales / High sales proportion in both training and testing datasets.
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (2208, 18)
X_test shape: (553, 18)
y_train shape: (2208,)
y_test shape: (553,)

In [38]:
numerical_columns = X_train.select_dtypes(include="number").columns
categorical_columns = X_train.select_dtypes(include="object").columns

print("Numerical columns:")
print(numerical_columns)
print("-----------------------------------------------")
print("\nCategorical columns:")
print(categorical_columns)

Numerical columns:
Index(['Customer_Age', 'Quantity', 'Unit_Price', 'Discount_Pct',
       'Shipping_Days', 'Customer_Loyalty_Points', 'Website_Session_Minutes',
       'Items_Viewed', 'Previous_Orders'],
      dtype='str')
-----------------------------------------------

Categorical columns:
Index(['Customer_Segment', 'City', 'Region', 'Category', 'Product_Name',
       'Sales_Channel', 'Payment_Method', 'Device', 'Marketing_Source'],
      dtype='str')

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_5504\1891196760.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = X_train.select_dtypes(include="object").columns

In [39]:
for column in categorical_columns:
    X_train[column] = X_train[column].str.strip().str.title()
    X_test[column] = X_test[column].str.strip().str.title()

print("Categorical values cleaned.")

Categorical values cleaned.

In [40]:
import numpy as np

print("NaN values in X_train_processed:",
      np.isnan(X_train_processed).sum())

print("NaN values in X_test_processed:",
      np.isnan(X_test_processed).sum())

NaN values in X_train_processed: 0
NaN values in X_test_processed: 0

In [41]:
print(X_train[numerical_columns].isna().sum())

Customer_Age               85
Quantity                    0
Unit_Price                  0
Discount_Pct                0
Shipping_Days              82
Customer_Loyalty_Points    94
Website_Session_Minutes    62
Items_Viewed                0
Previous_Orders             0
dtype: int64

In [42]:
for column in numerical_columns:
    median_value = X_train[column].median()
    
    X_train[column] = X_train[column].fillna(median_value)
    X_test[column] = X_test[column].fillna(median_value) 

print(X_train[numerical_columns].isna().sum())
print("\nTest:")
print(X_test[numerical_columns].isna().sum())

Customer_Age               0
Quantity                   0
Unit_Price                 0
Discount_Pct               0
Shipping_Days              0
Customer_Loyalty_Points    0
Website_Session_Minutes    0
Items_Viewed               0
Previous_Orders            0
dtype: int64

Test:
Customer_Age               0
Quantity                   0
Unit_Price                 0
Discount_Pct               0
Shipping_Days              0
Customer_Loyalty_Points    0
Website_Session_Minutes    0
Items_Viewed               0
Previous_Orders            0
dtype: int64

In [43]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder

scaler = StandardScaler()
encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

# Numerical features
X_train_num = scaler.fit_transform(X_train[numerical_columns])
X_test_num = scaler.transform(X_test[numerical_columns])

# Categorical features
X_train_cat = encoder.fit_transform(X_train[categorical_columns])
X_test_cat = encoder.transform(X_test[categorical_columns])

print("Numerical training shape:", X_train_num.shape)
print("Categorical training shape:", X_train_cat.shape)

print("Numerical test shape:", X_test_num.shape)
print("Categorical test shape:", X_test_cat.shape)

Numerical training shape: (2208, 9)
Categorical training shape: (2208, 58)
Numerical test shape: (553, 9)
Categorical test shape: (553, 58)

In [44]:
import numpy as np

X_train_processed = np.hstack([
    X_train_num,
    X_train_cat
])

X_test_processed = np.hstack([
    X_test_num,
    X_test_cat
])

print("X_train_processed:", X_train_processed.shape)
print("X_test_processed :", X_test_processed.shape)

X_train_processed: (2208, 67)
X_test_processed : (553, 67)

In [45]:
print("NaN values in X_train_processed:", np.isnan(X_train_processed).sum())
print("NaN values in X_test_processed :", np.isnan(X_test_processed).sum())

NaN values in X_train_processed: 0
NaN values in X_test_processed : 0

In [46]:
X_outlier_handled = X.copy()

for col in numerical_columns:
    Q1 = X_outlier_handled[col].quantile(0.25)
    Q3 = X_outlier_handled[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    median_value = X_outlier_handled[col].median()

    # Replace outliers with median
    X_outlier_handled.loc[
        (X_outlier_handled[col] < lower_bound) |
        (X_outlier_handled[col] > upper_bound),
        col
    ] = median_value

In [47]:
from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(max_iter=1000)

logistic_model.fit(
    X_train_processed,
    y_train
)

print("Logistic Regression model trained successfully.")

Logistic Regression model trained successfully.

In [48]:
y_pred = logistic_model.predict(X_test_processed)

print("Predictions generated successfully.")
print(y_pred[:10])

Predictions generated successfully.
['High sales' 'High sales' 'Low sales' 'High sales' 'High sales'
 'Low sales' 'Low sales' 'Low sales' 'Low sales' 'High sales']

In [49]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Logistic Regression Accuracy:", accuracy)
print("Accuracy (%):", accuracy * 100)

Logistic Regression Accuracy: 0.9041591320072333
Accuracy (%): 90.41591320072332

In [50]:
from sklearn.metrics import confusion_matrix, classification_report

cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[242  35]
 [ 18 258]]

Classification Report:
              precision    recall  f1-score   support

  High sales       0.93      0.87      0.90       277
   Low sales       0.88      0.93      0.91       276

    accuracy                           0.90       553
   macro avg       0.91      0.90      0.90       553
weighted avg       0.91      0.90      0.90       553

In [51]:
# (III.) KNN - Classification 

# Basic verification 

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nX columns:")
print(X.columns.tolist())

print("\ny distribution:")
print(y.value_counts())

X shape: (2761, 18)
y shape: (2761,)

X columns:
['Customer_Age', 'Customer_Segment', 'City', 'Region', 'Category', 'Product_Name', 'Sales_Channel', 'Payment_Method', 'Device', 'Quantity', 'Unit_Price', 'Discount_Pct', 'Shipping_Days', 'Marketing_Source', 'Customer_Loyalty_Points', 'Website_Session_Minutes', 'Items_Viewed', 'Previous_Orders']

y distribution:
Sales_Category
High sales    1381
Low sales     1380
Name: count, dtype: int64

In [52]:
# Train - test split 

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    train_size=0.80,
    random_state=34,
    stratify=y
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (2208, 18)
X_test shape: (553, 18)
y_train shape: (2208,)
y_test shape: (553,)

In [53]:
numerical_columns = X_train.select_dtypes(include="number").columns
categorical_columns = X_train.select_dtypes(include="object").columns

print("Numerical columns:")
print(numerical_columns.tolist())

print("\nCategorical columns:")
print(categorical_columns.tolist())

print("\nNumber of numerical columns:", len(numerical_columns))
print("Number of categorical columns:", len(categorical_columns))

Numerical columns:
['Customer_Age', 'Quantity', 'Unit_Price', 'Discount_Pct', 'Shipping_Days', 'Customer_Loyalty_Points', 'Website_Session_Minutes', 'Items_Viewed', 'Previous_Orders']

Categorical columns:
['Customer_Segment', 'City', 'Region', 'Category', 'Product_Name', 'Sales_Channel', 'Payment_Method', 'Device', 'Marketing_Source']

Number of numerical columns: 9
Number of categorical columns: 9

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_5504\979843410.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = X_train.select_dtypes(include="object").columns

In [54]:
print("Missing values in X_train:")
print(X_train.isnull().sum())

print("\nMissing values in X_test:")
print(X_test.isnull().sum())

Missing values in X_train:
Customer_Age               85
Customer_Segment            0
City                       51
Region                      0
Category                    0
Product_Name                0
Sales_Channel               0
Payment_Method             49
Device                      0
Quantity                    0
Unit_Price                  0
Discount_Pct                0
Shipping_Days              82
Marketing_Source            0
Customer_Loyalty_Points    94
Website_Session_Minutes    62
Items_Viewed                0
Previous_Orders             0
dtype: int64

Missing values in X_test:
Customer_Age               29
Customer_Segment            0
City                       20
Region                      0
Category                    0
Product_Name                0
Sales_Channel               0
Payment_Method             17
Device                      0
Quantity                    0
Unit_Price                  0
Discount_Pct                0
Shipping_Days              17
Marketing_Source            0
Customer_Loyalty_Points    17
Website_Session_Minutes    10
Items_Viewed                0
Previous_Orders             0
dtype: int64

In [55]:
# Fill Numerical Missing Values

for column in numerical_columns:
    median_value = X_train[column].median()

    X_train[column] = X_train[column].fillna(median_value)
    X_test[column] = X_test[column].fillna(median_value)

print("Missing numerical values in X_train:")
print(X_train[numerical_columns].isnull().sum())

print("\nMissing numerical values in X_test:")
print(X_test[numerical_columns].isnull().sum())

Missing numerical values in X_train:
Customer_Age               0
Quantity                   0
Unit_Price                 0
Discount_Pct               0
Shipping_Days              0
Customer_Loyalty_Points    0
Website_Session_Minutes    0
Items_Viewed               0
Previous_Orders            0
dtype: int64

Missing numerical values in X_test:
Customer_Age               0
Quantity                   0
Unit_Price                 0
Discount_Pct               0
Shipping_Days              0
Customer_Loyalty_Points    0
Website_Session_Minutes    0
Items_Viewed               0
Previous_Orders            0
dtype: int64

In [56]:
#  Fill Categorical Missing Values 

for column in categorical_columns:
    mode_value = X_train[column].mode()[0]

    X_train[column] = X_train[column].fillna(mode_value)
    X_test[column] = X_test[column].fillna(mode_value)

print("Missing categorical values in X_train:")
print(X_train[categorical_columns].isnull().sum())

print("\nMissing categorical values in X_test:")
print(X_test[categorical_columns].isnull().sum())

Missing categorical values in X_train:
Customer_Segment    0
City                0
Region              0
Category            0
Product_Name        0
Sales_Channel       0
Payment_Method      0
Device              0
Marketing_Source    0
dtype: int64

Missing categorical values in X_test:
Customer_Segment    0
City                0
Region              0
Category            0
Product_Name        0
Sales_Channel       0
Payment_Method      0
Device              0
Marketing_Source    0
dtype: int64

In [57]:
for column in categorical_columns:
    X_train[column] = X_train[column].str.strip().str.title()
    X_test[column] = X_test[column].str.strip().str.title()

In [58]:
X_outlier_handled = X.copy()

for col in numerical_columns:

    # Calculate bounds from original data
    Q1 = X[col].quantile(0.25)
    Q3 = X[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    median_value = X[col].median()

    # Replace original outliers with median
    outlier_mask = (
        (X[col] < lower_bound) |
        (X[col] > upper_bound)
    )

    X_outlier_handled.loc[outlier_mask, col] = median_value

In [59]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_num = scaler.fit_transform(X_train[numerical_columns])
X_test_num = scaler.transform(X_test[numerical_columns])

print("X_train_num shape:", X_train_num.shape)
print("X_test_num shape:", X_test_num.shape)

X_train_num shape: (2208, 9)
X_test_num shape: (553, 9)

In [60]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

X_train_cat = encoder.fit_transform(X_train[categorical_columns])
X_test_cat = encoder.transform(X_test[categorical_columns])

print("X_train_cat shape:", X_train_cat.shape)
print("X_test_cat shape:", X_test_cat.shape)

X_train_cat shape: (2208, 56)
X_test_cat shape: (553, 56)

In [61]:
import numpy as np

X_train_processed = np.hstack([
    X_train_num,
    X_train_cat
])

X_test_processed = np.hstack([
    X_test_num,
    X_test_cat
])

print("X_train_processed shape:", X_train_processed.shape)
print("X_test_processed shape:", X_test_processed.shape)

X_train_processed shape: (2208, 65)
X_test_processed shape: (553, 65)

In [62]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

k_values = range(1, 40, 2)
cv_accuracy = []

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)

    scores = cross_val_score(
        knn,
        X_train_processed,
        y_train,
        cv=5,
        scoring="accuracy"
    )

    cv_accuracy.append(scores.mean())

current_highest_accuray_value = 0
k_max = 0
for k, accuracy in zip(k_values, cv_accuracy):
    if (accuracy > current_highest_accuray_value):
        current_highest_accuray_value = accuracy
        k_max = k
    print(f"K = {k}, CV Accuracy = {accuracy:.4f}") 
print("-------------------------------------------------")
print("Best accuracy among all k-values: ", k_max)

K = 1, CV Accuracy = 0.6617
K = 3, CV Accuracy = 0.6879
K = 5, CV Accuracy = 0.7133
K = 7, CV Accuracy = 0.7228
K = 9, CV Accuracy = 0.7405
K = 11, CV Accuracy = 0.7491
K = 13, CV Accuracy = 0.7423
K = 15, CV Accuracy = 0.7577
K = 17, CV Accuracy = 0.7586
K = 19, CV Accuracy = 0.7668
K = 21, CV Accuracy = 0.7726
K = 23, CV Accuracy = 0.7708
K = 25, CV Accuracy = 0.7717
K = 27, CV Accuracy = 0.7758
K = 29, CV Accuracy = 0.7763
K = 31, CV Accuracy = 0.7772
K = 33, CV Accuracy = 0.7790
K = 35, CV Accuracy = 0.7880
K = 37, CV Accuracy = 0.7835
K = 39, CV Accuracy = 0.7831
-------------------------------------------------
Best accuracy among all k-values:  35

In [63]:
# Training model 

from sklearn.neighbors import KNeighborsClassifier

knn_classifier = KNeighborsClassifier(n_neighbors=35)

knn_classifier.fit(X_train_processed, y_train)

print("KNN Classification model trained successfully.")

KNN Classification model trained successfully.

In [64]:
y_pred = knn_classifier.predict(X_test_processed)

print("First 10 predictions:")
print(y_pred[:10])

First 10 predictions:
['High sales' 'High sales' 'Low sales' 'High sales' 'Low sales'
 'Low sales' 'Low sales' 'Low sales' 'Low sales' 'Low sales']

In [65]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("KNN Classification Accuracy:", accuracy)
print("KNN Classification Accuracy (%):", accuracy * 100)

KNN Classification Accuracy: 0.779385171790235
KNN Classification Accuracy (%): 77.9385171790235

In [66]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[195  82]
 [ 40 236]]

In [67]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

  High sales       0.83      0.70      0.76       277
   Low sales       0.74      0.86      0.79       276

    accuracy                           0.78       553
   macro avg       0.79      0.78      0.78       553
weighted avg       0.79      0.78      0.78       553

In [68]:
# (IV.) KNN - Regression 

y_reg = df["Net_Sales"]

y_train_reg = y_reg.loc[X_train.index]
y_test_reg = y_reg.loc[X_test.index]

print("y_train_reg shape:", y_train_reg.shape)
print("y_test_reg shape:", y_test_reg.shape)

y_train_reg shape: (2208,)
y_test_reg shape: (553,)

In [69]:
print(y_reg.describe())

count      2761.000000
mean       4424.295657
std        7645.791370
min       -6840.480000
25%        1020.090000
50%        2285.970000
75%        4844.620000
max      199210.220000
Name: Net_Sales, dtype: float64

In [70]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import cross_val_score
import numpy as np

k_values = range(1, 40, 2)
cv_rmse = []

for k in k_values:
    knn = KNeighborsRegressor(n_neighbors=k)

    scores = cross_val_score(
        knn,
        X_train_processed,
        y_train_reg,
        cv=5,
        scoring="neg_root_mean_squared_error"
    )

    cv_rmse.append(-scores.mean())

for k, rmse in zip(k_values, cv_rmse):
    if k == 1:
        lowest_k = k
        lowest_rmse_value = rmse 
    else:
        if (rmse < lowest_rmse_value):
            lowest_k = k 
            lowest_rmse_value = rmse 
    print(f"K = {k}, CV RMSE = {rmse:.2f}")

print("--------------------------------------------") 
print("K with best accuracy among all: ", lowest_k) 
print("Lowest rmse value: ", lowest_rmse_value)

K = 1, CV RMSE = 4458.62
K = 3, CV RMSE = 3641.60
K = 5, CV RMSE = 3604.60
K = 7, CV RMSE = 3653.84
K = 9, CV RMSE = 3668.92
K = 11, CV RMSE = 3720.06
K = 13, CV RMSE = 3768.02
K = 15, CV RMSE = 3818.68
K = 17, CV RMSE = 3847.56
K = 19, CV RMSE = 3851.47
K = 21, CV RMSE = 3885.59
K = 23, CV RMSE = 3909.98
K = 25, CV RMSE = 3936.38
K = 27, CV RMSE = 3961.90
K = 29, CV RMSE = 3981.76
K = 31, CV RMSE = 4008.65
K = 33, CV RMSE = 4033.71
K = 35, CV RMSE = 4062.31
K = 37, CV RMSE = 4080.38
K = 39, CV RMSE = 4103.10
--------------------------------------------
K with best accuracy among all:  5
Lowest rmse value:  3604.598916180348

In [71]:
# Train the KNN Regression Model 

from sklearn.neighbors import KNeighborsRegressor

knn_regressor = KNeighborsRegressor(n_neighbors=5)

knn_regressor.fit(X_train_processed, y_train_reg)

print("KNN Regression model trained successfully.")

KNN Regression model trained successfully.

In [72]:
y_pred_reg = knn_regressor.predict(X_test_processed)

print("First 10 predictions:")
print(y_pred_reg[:10])

First 10 predictions:
[4150.676 5029.776 1187.414 2965.144 2789.954 3189.174 1865.192 2048.45
 1173.158 1531.67 ]

In [73]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test_reg, y_pred_reg)
mse = mean_squared_error(y_test_reg, y_pred_reg)
rmse = np.sqrt(mse)
r2 = r2_score(y_test_reg, y_pred_reg)

print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R²  :", r2)

MAE : 2561.0827233273053
MSE : 68417202.42840686
RMSE: 8271.469181977702
R²  : 0.49559759758492605

In [74]:
# (V.) Decision tree for classification 

print("Decision Tree Classification prerequisites")
print("------------------------------------------")
print("Dataset       :", df.shape)
print("Features      :", X.shape)
print("Target        :", y.shape)
print("Train data    :", X_train.shape)
print("Test data     :", X_test.shape)
print("Target classes:", y.unique())
print("Missing X     :", X.isnull().sum().sum())
print("Missing y     :", y.isnull().sum())

Decision Tree Classification prerequisites
------------------------------------------
Dataset       : (2761, 33)
Features      : (2761, 18)
Target        : (2761,)
Train data    : (2208, 18)
Test data     : (553, 18)
Target classes: <ArrowStringArray>
['Low sales', 'High sales']
Length: 2, dtype: str
Missing X     : 533
Missing y     : 0

In [75]:
X_train_clean = X_train.copy()
X_test_clean = X_test.copy()

for col in numerical_columns:
    median_value = X_train_clean[col].median()
    X_train_clean[col] = X_train_clean[col].fillna(median_value)
    X_test_clean[col] = X_test_clean[col].fillna(median_value)

for col in categorical_columns:
    mode_value = X_train_clean[col].mode()[0]
    X_train_clean[col] = X_train_clean[col].fillna(mode_value)
    X_test_clean[col] = X_test_clean[col].fillna(mode_value)

print("Missing values in X_train:", X_train_clean.isnull().sum().sum())
print("Missing values in X_test :", X_test_clean.isnull().sum().sum())

Missing values in X_train: 0
Missing values in X_test : 0

In [76]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

X_train_cat = encoder.fit_transform(
    X_train_clean[categorical_columns]
)

X_test_cat = encoder.transform(
    X_test_clean[categorical_columns]
)

print("Encoded training shape:", X_train_cat.shape)
print("Encoded testing shape :", X_test_cat.shape)

Encoded training shape: (2208, 56)
Encoded testing shape : (553, 56)

In [77]:
X_train_num = X_train_clean[numerical_columns].to_numpy()
X_test_num = X_test_clean[numerical_columns].to_numpy()

X_train_processed = np.hstack([
    X_train_num,
    X_train_cat
])

X_test_processed = np.hstack([
    X_test_num,
    X_test_cat
])

print("Final training shape:", X_train_processed.shape)
print("Final testing shape :", X_test_processed.shape)

Final training shape: (2208, 65)
Final testing shape : (553, 65)

In [78]:
from sklearn.tree import DecisionTreeClassifier

dt_classifier = DecisionTreeClassifier(
    criterion="gini",
    random_state=34
)

dt_classifier.fit(
    X_train_processed,
    y_train
)
print("Decision Tree training completed.")

Decision Tree training completed.

In [79]:
y_pred_dt = dt_classifier.predict(X_test_processed)

print("Predictions generated:", len(y_pred_dt))
print("\nFirst 10 predictions:")
print(y_pred_dt[:10])

Predictions generated: 553

First 10 predictions:
['High sales' 'High sales' 'Low sales' 'High sales' 'High sales'
 'Low sales' 'Low sales' 'Low sales' 'Low sales' 'High sales']

In [80]:
from sklearn.metrics import accuracy_score

accuracy_dt = accuracy_score(y_test, y_pred_dt)

print("Decision Tree Accuracy:", accuracy_dt)
print("Decision Tree Accuracy (%):", accuracy_dt * 100)

Decision Tree Accuracy: 0.9602169981916817
Decision Tree Accuracy (%): 96.02169981916818

In [81]:
y_train_pred_dt = dt_classifier.predict(X_train_processed)

train_accuracy_dt = accuracy_score(
    y_train,
    y_train_pred_dt
)

test_accuracy_dt = accuracy_score(
    y_test,
    y_pred_dt
)

print("Training Accuracy:", train_accuracy_dt)
print("Testing Accuracy :", test_accuracy_dt)

Training Accuracy: 1.0
Testing Accuracy : 0.9602169981916817

In [82]:
# (VI.) Decision tree for regression   

from sklearn.tree import DecisionTreeRegressor 

decision_tree_regressor = DecisionTreeRegressor(
    random_state=34
)

print(decision_tree_regressor)

DecisionTreeRegressor(random_state=34)

In [83]:
decision_tree_regressor.fit(
    X_train_processed,
    y_train_reg
)

print("Decision Tree Regression model trained successfully.")

Decision Tree Regression model trained successfully.

In [84]:
y_pred_dt_reg = decision_tree_regressor.predict(
    X_test_processed
)

print("Predictions generated:", len(y_pred_dt_reg))

print("\nFirst 10 predictions:")
print(y_pred_dt_reg[:10])

Predictions generated: 553

First 10 predictions:
[3878.24 7432.11  398.91 2947.99 3241.72 1169.22  870.72  126.43 1587.86
 3277.7 ]

In [85]:
mae_dt_reg = mean_absolute_error(
    y_test_reg,
    y_pred_dt_reg
)

mse_dt_reg = mean_squared_error(
    y_test_reg,
    y_pred_dt_reg
)

rmse_dt_reg = np.sqrt(mse_dt_reg)

r2_dt_reg = r2_score(
    y_test_reg,
    y_pred_dt_reg
)

print("MAE :", mae_dt_reg)
print("MSE :", mse_dt_reg)
print("RMSE:", rmse_dt_reg)
print("R²  :", r2_dt_reg)

MAE : 868.7254611211573
MSE : 51150661.37387703
RMSE: 7151.969055713052
R²  : 0.6228943077714748

In [86]:
y_train_pred_dt_reg = decision_tree_regressor.predict(
    X_train_processed
)

train_r2_dt_reg = r2_score(
    y_train_reg,
    y_train_pred_dt_reg
)

test_r2_dt_reg = r2_score(
    y_test_reg,
    y_pred_dt_reg
)

print("Training R²:", train_r2_dt_reg)
print("Testing R² :", test_r2_dt_reg)

Training R²: 1.0
Testing R² : 0.6228943077714748

In [87]:
# (VII.) Random forest for classification  

from sklearn.ensemble import RandomForestClassifier 

random_forest_classifier = RandomForestClassifier(
    n_estimators=100,
    random_state=34
)

random_forest_classifier.fit(
    X_train_processed,
    y_train
)

print("Random Forest Classification model trained successfully.")

Random Forest Classification model trained successfully.

In [88]:
y_pred_rf = random_forest_classifier.predict(
    X_test_processed
)

print("Predictions generated:", len(y_pred_rf))

print("\nFirst 10 predictions:")
print(y_pred_rf[:10])

Predictions generated: 553

First 10 predictions:
['High sales' 'High sales' 'Low sales' 'High sales' 'High sales'
 'Low sales' 'Low sales' 'Low sales' 'Low sales' 'High sales']

In [89]:
accuracy_rf = accuracy_score(
    y_test,
    y_pred_rf
)

print("Random Forest Accuracy:", accuracy_rf)
print("Random Forest Accuracy (%):", accuracy_rf * 100)

Random Forest Accuracy: 0.9439421338155516
Random Forest Accuracy (%): 94.39421338155516

In [90]:
cm_rf = confusion_matrix(
    y_test,
    y_pred_rf
)

print("Confusion Matrix:")
print(cm_rf)

Confusion Matrix:
[[257  20]
 [ 11 265]]

In [91]:
print("Classification Report:")
print(
    classification_report(
        y_test,
        y_pred_rf
    )
)

Classification Report:
              precision    recall  f1-score   support

  High sales       0.96      0.93      0.94       277
   Low sales       0.93      0.96      0.94       276

    accuracy                           0.94       553
   macro avg       0.94      0.94      0.94       553
weighted avg       0.94      0.94      0.94       553

In [92]:
y_train_pred_rf = random_forest_classifier.predict(
    X_train_processed
)

train_accuracy_rf = accuracy_score(
    y_train,
    y_train_pred_rf
)

test_accuracy_rf = accuracy_score(
    y_test,
    y_pred_rf
)

print("Training Accuracy:", train_accuracy_rf)
print("Testing Accuracy :", test_accuracy_rf)

Training Accuracy: 1.0
Testing Accuracy : 0.9439421338155516

In [93]:
# (VIII.) Random forest for regression 

from sklearn.ensemble import RandomForestRegressor 

random_forest_regressor = RandomForestRegressor(
    n_estimators=100,
    random_state=34
)

random_forest_regressor.fit(
    X_train_processed,
    y_train_reg
)

print("Random Forest Regression model trained successfully.")

Random Forest Regression model trained successfully.

In [94]:
y_pred_rf_reg = random_forest_regressor.predict(
    X_test_processed
)

print("Predictions generated:", len(y_pred_rf_reg))

print("\nFirst 10 predictions:")
print(y_pred_rf_reg[:10])

Predictions generated: 553

First 10 predictions:
[3853.2247 6860.347   385.4927 3096.4994 3388.0392 1192.2992  659.7438
  198.4065 1546.0186 3270.8751]

In [95]:
mae_rf_reg = mean_absolute_error(
    y_test_reg,
    y_pred_rf_reg
)

mse_rf_reg = mean_squared_error(
    y_test_reg,
    y_pred_rf_reg
)

rmse_rf_reg = np.sqrt(mse_rf_reg)

r2_rf_reg = r2_score(
    y_test_reg,
    y_pred_rf_reg
)

print("MAE :", mae_rf_reg)
print("MSE :", mse_rf_reg)
print("RMSE:", rmse_rf_reg)
print("R²  :", r2_rf_reg)

MAE : 785.1517502712478
MSE : 57033062.1659719
RMSE: 7552.023713281884
R²  : 0.579526602191788

In [96]:
y_train_pred_rf_reg = random_forest_regressor.predict(
    X_train_processed
)

train_r2_rf_reg = r2_score(
    y_train_reg,
    y_train_pred_rf_reg
)

test_r2_rf_reg = r2_score(
    y_test_reg,
    y_pred_rf_reg
)

print("Training R²:", train_r2_rf_reg)
print("Testing R² :", test_r2_rf_reg)

Training R²: 0.9914924679812144
Testing R² : 0.579526602191788

In [97]:
# (IX.) Support vector machine for classification 

from sklearn.svm import SVC 

svm_classifier = SVC(
    kernel="rbf",
    C=1.0,
    random_state=34
)

svm_classifier.fit(
    X_train_processed,
    y_train
)

print("SVM Classification model trained successfully.")

SVM Classification model trained successfully.

In [98]:
y_pred_svm = svm_classifier.predict(
    X_test_processed
)

print("Predictions generated:", len(y_pred_svm))

print("\nFirst 10 predictions:")
print(y_pred_svm[:10])

Predictions generated: 553

First 10 predictions:
['High sales' 'High sales' 'Low sales' 'Low sales' 'Low sales' 'Low sales'
 'Low sales' 'Low sales' 'Low sales' 'High sales']

In [99]:
accuracy_svm = accuracy_score(
    y_test,
    y_pred_svm
)

print("SVM Accuracy:", accuracy_svm)
print("SVM Accuracy (%):", accuracy_svm * 100)

SVM Accuracy: 0.864376130198915
SVM Accuracy (%): 86.4376130198915

In [100]:
cm_svm = confusion_matrix(
    y_test,
    y_pred_svm
)

print("Confusion Matrix:")
print(cm_svm)

Confusion Matrix:
[[232  45]
 [ 30 246]]

In [101]:
print("Classification Report:")

print(
    classification_report(
        y_test,
        y_pred_svm
    )
)

Classification Report:
              precision    recall  f1-score   support

  High sales       0.89      0.84      0.86       277
   Low sales       0.85      0.89      0.87       276

    accuracy                           0.86       553
   macro avg       0.87      0.86      0.86       553
weighted avg       0.87      0.86      0.86       553

In [102]:
y_train_pred_svm = svm_classifier.predict(
    X_train_processed
)

train_accuracy_svm = accuracy_score(
    y_train,
    y_train_pred_svm
)

test_accuracy_svm = accuracy_score(
    y_test,
    y_pred_svm
)

print("Training Accuracy:", train_accuracy_svm)
print("Testing Accuracy :", test_accuracy_svm)

Training Accuracy: 0.8491847826086957
Testing Accuracy : 0.864376130198915

In [103]:
# (X.) Support vector machine for Regression 

from sklearn.svm import SVR 

svm_regressor = SVR(
    kernel="rbf",
    C=100,
    epsilon=0.1
)

svm_regressor.fit(
    X_train_processed,
    y_train_reg
)

print("SVM Regression model trained successfully.")

SVM Regression model trained successfully.

In [104]:
y_pred_svm_reg = svm_regressor.predict(
    X_test_processed
)

print("Predictions generated:", len(y_pred_svm_reg))

print("\nFirst 10 predictions:")
print(y_pred_svm_reg[:10])

Predictions generated: 553

First 10 predictions:
[2504.37852825 2956.00195116  736.20223693 2003.2512669  2502.96068887
 1597.38134506 1997.62504777  391.1620671  1430.71765927 3346.5365948 ]

In [105]:
mae_svm_reg = mean_absolute_error(
    y_test_reg,
    y_pred_svm_reg
)

mse_svm_reg = mean_squared_error(
    y_test_reg,
    y_pred_svm_reg
)

rmse_svm_reg = np.sqrt(mse_svm_reg)

r2_svm_reg = r2_score(
    y_test_reg,
    y_pred_svm_reg
)

print("MAE :", mae_svm_reg)
print("MSE :", mse_svm_reg)
print("RMSE:", rmse_svm_reg)
print("R²  :", r2_svm_reg)

MAE : 2390.246706875464
MSE : 114368873.45065664
RMSE: 10694.338383025695
R²  : 0.1568212016505265

In [106]:
y_train_pred_svm_reg = svm_regressor.predict(
    X_train_processed
)

train_r2_svm_reg = r2_score(
    y_train_reg,
    y_train_pred_svm_reg
)

test_r2_svm_reg = r2_score(
    y_test_reg,
    y_pred_svm_reg
)

print("Training R²:", train_r2_svm_reg)
print("Testing R² :", test_r2_svm_reg)

Training R²: 0.4396822212643562
Testing R² : 0.1568212016505265

In [107]:
# (XI.) Bagging 

from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor 

base_model = DecisionTreeRegressor(
    random_state=34
) 

bagging_regressor = BaggingRegressor(
    estimator=base_model,
    n_estimators=100,
    max_samples=1.0,
    max_features=1.0,
    bootstrap=True,
    random_state=34
) 

bagging_regressor.fit(
    X_train_processed,
    y_train_reg
)

print("Bagging Regression training completed.")

Bagging Regression training completed.

In [108]:
y_pred_bagging = bagging_regressor.predict(
    X_test_processed
)

print("First 10 predictions:")
print(y_pred_bagging[:10])

First 10 predictions:
[3878.1218 6971.6142  394.1327 3087.259  3385.1434 1191.0473  586.219
  194.711  1534.2008 3258.3587]

In [109]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
import numpy as np

mae_bagging = mean_absolute_error(
    y_test_reg,
    y_pred_bagging
)

mse_bagging = mean_squared_error(
    y_test_reg,
    y_pred_bagging
)

rmse_bagging = np.sqrt(mse_bagging)

r2_bagging = r2_score(
    y_test_reg,
    y_pred_bagging
)

print("Bagging Regression")
print("------------------")
print("MAE :", mae_bagging)
print("MSE :", mse_bagging)
print("RMSE:", rmse_bagging)
print("R²  :", r2_bagging)

Bagging Regression
------------------
MAE : 783.592225858951
MSE : 57203218.58118383
RMSE: 7563.280940252307
R²  : 0.5782721325325083

In [110]:
# (XII.) Gradient Boosting for regression

from sklearn.ensemble import GradientBoostingRegressor 

boosting_model = GradientBoostingRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=34
)

boosting_model

GradientBoostingRegressor(random_state=34)

In [111]:
boosting_model.fit(X_train_processed, y_train_reg)

y_pred_boosting = boosting_model.predict(X_test_processed)

print("First 10 Boosting predictions:")
print(y_pred_boosting[:10])

First 10 Boosting predictions:
[3709.94160812 6652.65042611  159.7826034  3013.85643531 3226.50720466
 1025.21703703  794.32246058  180.08075094 1481.13401784 3133.74963919]

In [112]:
mae_boosting = mean_absolute_error(y_test_reg, y_pred_boosting)
mse_boosting = mean_squared_error(y_test_reg, y_pred_boosting)
rmse_boosting = np.sqrt(mse_boosting)
r2_boosting = r2_score(y_test_reg, y_pred_boosting)

print("MAE :", mae_boosting)
print("MSE :", mse_boosting)
print("RMSE:", rmse_boosting)
print("R²  :", r2_boosting)

MAE : 789.5627189889691
MSE : 49056552.21080879
RMSE: 7004.038278793798
R²  : 0.6383330228209003

In [113]:
# (XIII.) Gradient Boosting for classification 

from sklearn.ensemble import GradientBoostingClassifier 

gb_classifier = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=34
) 

gb_classifier.fit(X_train_processed, y_train)

y_pred_gb_class = gb_classifier.predict(X_test_processed)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

accuracy = accuracy_score(y_test, y_pred_gb_class)
precision = precision_score(y_test, y_pred_gb_class, average="weighted")
recall = recall_score(y_test, y_pred_gb_class, average="weighted")
f1 = f1_score(y_test, y_pred_gb_class, average="weighted")

print("Gradient Boosting Classification")
print("--------------------------------")
print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

Gradient Boosting Classification
--------------------------------
Accuracy  : 0.9855
Precision : 0.9856
Recall    : 0.9855
F1 Score  : 0.9855

In [114]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_gb_class))

Confusion Matrix:
[[272   5]
 [  3 273]]

In [115]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred_gb_class))

Classification Report:
              precision    recall  f1-score   support

  High sales       0.99      0.98      0.99       277
   Low sales       0.98      0.99      0.99       276

    accuracy                           0.99       553
   macro avg       0.99      0.99      0.99       553
weighted avg       0.99      0.99      0.99       553

In [116]:
# (XIV.) Adaptive Boostive  for regression


from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor 

base_model = DecisionTreeRegressor(
    max_depth=3,
    random_state=34
) 

adaboost_regressor = AdaBoostRegressor(
    estimator=base_model,
    n_estimators=100,
    learning_rate=0.1,
    random_state=34
) 

adaboost_regressor.fit(
    X_train_processed,
    y_train_reg
) 

y_pred_adaboost = adaboost_regressor.predict(
    X_test_processed
) 

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
import numpy as np

mae = mean_absolute_error(
    y_test_reg,
    y_pred_adaboost
)

mse = mean_squared_error(
    y_test_reg,
    y_pred_adaboost
)

rmse = np.sqrt(mse)

r2 = r2_score(
    y_test_reg,
    y_pred_adaboost
)

print("AdaBoost Regression")
print("-------------------")
print(f"MAE : {mae}")
print(f"MSE : {mse}")
print(f"RMSE: {rmse}")
print(f"R²  : {r2}")

AdaBoost Regression
-------------------
MAE : 2116.711187339536
MSE : 60747854.29925083
RMSE: 7794.090986077263
R²  : 0.5521394830172026

In [117]:
# XV. AdaBoost — Classification  

from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier  

base_model = DecisionTreeClassifier(
    max_depth=1,
    random_state=34
)  

adaboost_classifier = AdaBoostClassifier(
    estimator=base_model,
    n_estimators=100,
    learning_rate=0.1,
    random_state=34
) 

adaboost_classifier.fit(
    X_train_processed,
    y_train
)  

y_pred_adaboost_class = adaboost_classifier.predict(
    X_test_processed
)

In [118]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

accuracy = accuracy_score(
    y_test,
    y_pred_adaboost_class
)

precision = precision_score(
    y_test,
    y_pred_adaboost_class,
    average="weighted"
)

recall = recall_score(
    y_test,
    y_pred_adaboost_class,
    average="weighted"
)

f1 = f1_score(
    y_test,
    y_pred_adaboost_class,
    average="weighted"
)

print("AdaBoost Classification")
print("-----------------------")
print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

AdaBoost Classification
-----------------------
Accuracy  : 0.9367
Precision : 0.9369
Recall    : 0.9367
F1 Score  : 0.9367

In [119]:
cm = confusion_matrix(
    y_test,
    y_pred_adaboost_class
)

print("\nConfusion Matrix:")
print(cm)

Confusion Matrix:
[[257  20]
 [ 15 261]]

In [120]:
print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_adaboost_class
    )
)

Classification Report:
              precision    recall  f1-score   support

  High sales       0.94      0.93      0.94       277
   Low sales       0.93      0.95      0.94       276

    accuracy                           0.94       553
   macro avg       0.94      0.94      0.94       553
weighted avg       0.94      0.94      0.94       553

In [121]:
regression_comparison = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "KNN Regression",
        "Decision Tree Regression",
        "SVM Regression",
        "Bagging Regression",
        "Random Forest Regression",
        "Gradient Boosting Regression",
        "AdaBoost Regression"
    ],
    "MAE": [
        1474.1967865909612,
        2561.0827233273053,
        868.73,
        2390.25,
        783.592225858951,
        785.15,
        789.5627189889691,
        2116.711187339536
    ],
    "MSE": [
        8849610.90,
        68417202.43,
        51150661.37,
        114368873.45,
        57203218.58118383,
        57033062.17,
        49056552.21080879,
        60747854.29925083
    ],
    "RMSE": [
        2974.8319111522865,
        8271.469181977702,
        7151.97,
        10694.34,
        7563.280940252307,
        7552.02,
        7004.038278793798,
        7794.090986077263
    ],
    "R²": [
        0.8180316569469919,
        0.49559759758492605,
        0.6229,
        0.1568,
        0.5782721325325083,
        0.5795,
        0.6383330228209003,
        0.5521394830172026
    ]
})

regression_comparison = (
    regression_comparison
    .sort_values("R²", ascending=False)
    .reset_index(drop=True)
)

regression_comparison.index = range(
    1,
    len(regression_comparison) + 1
)

regression_comparison.round(2)

                          Model      MAE           MSE      RMSE    R²
1             Linear Regression  1474.20  8.849611e+06   2974.83  0.82
2  Gradient Boosting Regression   789.56  4.905655e+07   7004.04  0.64
3      Decision Tree Regression   868.73  5.115066e+07   7151.97  0.62
4      Random Forest Regression   785.15  5.703306e+07   7552.02  0.58
5            Bagging Regression   783.59  5.720322e+07   7563.28  0.58
6           AdaBoost Regression  2116.71  6.074785e+07   7794.09  0.55
7                KNN Regression  2561.08  6.841720e+07   8271.47  0.50
8                SVM Regression  2390.25  1.143689e+08  10694.34  0.16

In [122]:
classification_comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "KNN Classification",
        "Decision Tree Classification",
        "SVM Classification",
        "Random Forest Classification",
        "Gradient Boosting Classification",
        "AdaBoost Classification"
    ],
    "Accuracy": [
        0.9041591320072333,
        0.779385171790235,
        0.9602169981916817,
        0.864376130198915,
        0.9439421338155516,
        0.9855,
        0.9367
    ]
})

classification_comparison = (
    classification_comparison
    .sort_values("Accuracy", ascending=False)
    .reset_index(drop=True)
)

classification_comparison.index = range(
    1,
    len(classification_comparison) + 1
)

classification_comparison["Accuracy"] = (
    classification_comparison["Accuracy"] * 100
).round(2)

classification_comparison

                              Model  Accuracy
1  Gradient Boosting Classification     98.55
2      Decision Tree Classification     96.02
3      Random Forest Classification     94.39
4           AdaBoost Classification     93.67
5               Logistic Regression     90.42
6                SVM Classification     86.44
7                KNN Classification     77.94