In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("House Price Prediction Dataset.csv")

In [2]:
print(df.shape) 
print("------------------------------------------------")
print(df.columns)

(2000, 10)
------------------------------------------------
Index(['Id', 'Area', 'Bedrooms', 'Bathrooms', 'Floors', 'YearBuilt',
       'Location', 'Condition', 'Garage', 'Price'],
      dtype='str')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id         2000 non-null   int64
 1   Area       2000 non-null   int64
 2   Bedrooms   2000 non-null   int64
 3   Bathrooms  2000 non-null   int64
 4   Floors     2000 non-null   int64
 5   YearBuilt  2000 non-null   int64
 6   Location   2000 non-null   str
 7   Condition  2000 non-null   str
 8   Garage     2000 non-null   str
 9   Price      2000 non-null   int64
dtypes: int64(7), str(3)
memory usage: 184.3 KB

In [4]:
df.describe()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Price
count,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000
mean,1000.500000,2786.209500,3.003500,2.55250,1.993500,1961.446000,537676.855000
std,577.494589,1295.146799,1.424606,1.10899,0.809188,35.926695,276428.845719
min,1.000000,501.000000,1.000000,1.00000,1.000000,1900.000000,50005.000000
25%,500.750000,1653.000000,2.000000,2.00000,1.000000,1930.000000,300098.000000
50%,1000.500000,2833.000000,3.000000,3.00000,2.000000,1961.000000,539254.000000
75%,1500.250000,3887.500000,4.000000,4.00000,3.000000,1993.000000,780086.000000
max,2000.000000,4999.000000,5.000000,4.00000,3.000000,2023.000000,999656.000000

In [5]:
df.isnull().sum()

Id           0
Area         0
Bedrooms     0
Bathrooms    0
Floors       0
YearBuilt    0
Location     0
Condition    0
Garage       0
Price        0
dtype: int64

In [6]:
print(df.duplicated().sum())

0

In [7]:
print(df.nunique())

Id           2000
Area         1622
Bedrooms        5
Bathrooms       4
Floors          3
YearBuilt     124
Location        4
Condition       4
Garage          2
Price        1999
dtype: int64

In [8]:
df["Building_Age"] = 2026 - df["YearBuilt"]
df = df.drop(columns=["YearBuilt"])

X = df.drop(columns=["Price", "Id"])
y = df["Price"]

In [9]:
X = df.drop(columns=["Price", "Id"])
y = df["Price"]

In [10]:
# Train-Test Split  

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=34
) 

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (1600, 8)
X_test : (400, 8)
y_train: (1600,)
y_test : (400,)

In [11]:
# Identify feature types 

numerical_columns = X_train.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_columns = X_train.select_dtypes(
    include=["object", "category"]
).columns.tolist()

print("Numerical Columns:")
print(numerical_columns)

print("\nCategorical Columns:")
print(categorical_columns) 

print("\nNumber of numerical features:", len(numerical_columns))
print("Number of categorical features:", len(categorical_columns))

Numerical Columns:
['Area', 'Bedrooms', 'Bathrooms', 'Floors', 'Building_Age']

Categorical Columns:
['Location', 'Condition', 'Garage']

Number of numerical features: 5
Number of categorical features: 3

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_7408\1079245108.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = X_train.select_dtypes(

In [12]:
# Feature scaling and label encoding 

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numerical_columns
        ),
        (
            "cat",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            ),
            categorical_columns
        )
    ]
) 

X_train_processed = preprocessor.fit_transform(X_train) 
X_test_processed = preprocessor.transform(X_test) 

print("X_train_processed shape:", X_train_processed.shape)
print("X_test_processed shape :", X_test_processed.shape)

X_train_processed shape: (1600, 15)
X_test_processed shape : (400, 15)

In [13]:
# I. Linear Regression 

from sklearn.linear_model import LinearRegression 
linear_model = LinearRegression() 

linear_model.fit(
    X_train_processed,
    y_train
)

y_pred_linear = linear_model.predict(
    X_test_processed
)

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
import numpy as np

mae_linear = mean_absolute_error(
    y_test,
    y_pred_linear
)

mse_linear = mean_squared_error(
    y_test,
    y_pred_linear
)

rmse_linear = np.sqrt(mse_linear)

r2_linear = r2_score(
    y_test,
    y_pred_linear
)

print("Linear Regression")
print("-----------------")
print(f"MAE : {mae_linear}")
print(f"MSE : {mse_linear}")
print(f"RMSE: {rmse_linear}")
print(f"R²  : {r2_linear}")

results = []

results.append({
    "Model": "Linear Regression",
    "MAE": mae_linear,
    "MSE": mse_linear,
    "RMSE": rmse_linear,
    "R²": r2_linear
})

Linear Regression
-----------------
MAE : 234637.1129757335
MSE : 74644832031.61607
RMSE: 273212.06421316037
R²  : 0.0010721120843308896

In [14]:
# II. Logistic Regression — Classification 

df["Price_Category"] = np.where(
    df["Price"] <= df["Price"].median(),
    "Low Price",
    "High Price"
) 

print(df[["Price", "Price_Category"]].head(10))

    Price Price_Category
0  149919      Low Price
1  424998      Low Price
2  266746      Low Price
3  244020      Low Price
4  636056     High Price
5   93262      Low Price
6  448722      Low Price
7  594893     High Price
8  652878     High Price
9  340375      Low Price

In [15]:
X_class = df.drop(columns=["Price", "Price_Category", "Id"])
y_class = df["Price_Category"] 

from sklearn.model_selection import train_test_split

X_train_class, X_test_class, y_train_class, y_test_class = train_test_split(
    X_class,
    y_class,
    test_size=0.2,
    random_state=34,
    stratify=y_class
) 

print("X_train_class:", X_train_class.shape)
print("X_test_class :", X_test_class.shape)
print("y_train_class:", y_train_class.shape)
print("y_test_class :", y_test_class.shape)

print("\nTraining class distribution:")
print(y_train_class.value_counts())

print("\nTesting class distribution:")
print(y_test_class.value_counts())

X_train_class: (1600, 8)
X_test_class : (400, 8)
y_train_class: (1600,)
y_test_class : (400,)

Training class distribution:
Price_Category
Low Price     800
High Price    800
Name: count, dtype: int64

Testing class distribution:
Price_Category
High Price    200
Low Price     200
Name: count, dtype: int64

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

classification_preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numerical_columns
        ),
        (
            "cat",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            ),
            categorical_columns
        )
    ]
) 

X_train_class_processed = classification_preprocessor.fit_transform(
    X_train_class
)

X_test_class_processed = classification_preprocessor.transform(
    X_test_class
) 

print(
    "X_train_class_processed:",
    X_train_class_processed.shape
)

print(
    "X_test_class_processed:",
    X_test_class_processed.shape
)

X_train_class_processed: (1600, 15)
X_test_class_processed: (400, 15)

In [17]:
from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(
    max_iter=1000,
    random_state=34
)

logistic_model.fit(
    X_train_class_processed,
    y_train_class
)

y_pred_logistic = logistic_model.predict(X_test_class_processed) 

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy_logistic = accuracy_score(
    y_test_class,
    y_pred_logistic
)

print("Accuracy:", accuracy_logistic)

print("\nClassification Report:")
print(classification_report(
    y_test_class,
    y_pred_logistic
))

print("\nConfusion Matrix:")
print(confusion_matrix(
    y_test_class,
    y_pred_logistic
))

Accuracy: 0.53

Classification Report:
              precision    recall  f1-score   support

  High Price       0.53      0.54      0.53       200
   Low Price       0.53      0.52      0.53       200

    accuracy                           0.53       400
   macro avg       0.53      0.53      0.53       400
weighted avg       0.53      0.53      0.53       400


Confusion Matrix:
[[108  92]
 [ 96 104]]

In [18]:
classification_results = [] 

classification_results.append({
    "Model": "Logistic Regression",
    "Accuracy": accuracy_logistic
})

In [19]:
# III. KNN — Classification 

from sklearn.neighbors import KNeighborsClassifier 

knn_class_model = KNeighborsClassifier(n_neighbors=5)

knn_class_model.fit(
    X_train_class_processed,
    y_train_class
) 

y_pred_knn_class = knn_class_model.predict(
    X_test_class_processed
)

In [20]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy_knn_class = accuracy_score(
    y_test_class,
    y_pred_knn_class
)

print("Accuracy:", accuracy_knn_class)

print("\nClassification Report:")
print(classification_report(
    y_test_class,
    y_pred_knn_class
))

print("\nConfusion Matrix:")
print(confusion_matrix(
    y_test_class,
    y_pred_knn_class
))

Accuracy: 0.5325

Classification Report:
              precision    recall  f1-score   support

  High Price       0.53      0.56      0.54       200
   Low Price       0.53      0.51      0.52       200

    accuracy                           0.53       400
   macro avg       0.53      0.53      0.53       400
weighted avg       0.53      0.53      0.53       400


Confusion Matrix:
[[111  89]
 [ 98 102]]

In [21]:
classification_results.append({
    "Model": "KNN Classification",
    "Accuracy": accuracy_knn_class
})

In [22]:
# IV. KNN — Regression 

from sklearn.neighbors import KNeighborsRegressor 

knn_reg_model = KNeighborsRegressor(
    n_neighbors=5
)

knn_reg_model.fit(
    X_train_processed,
    y_train
) 

y_pred_knn_reg = knn_reg_model.predict(
    X_test_processed
)

In [23]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae_knn_reg = mean_absolute_error(
    y_test,
    y_pred_knn_reg
)

mse_knn_reg = mean_squared_error(
    y_test,
    y_pred_knn_reg
)

rmse_knn_reg = np.sqrt(mse_knn_reg)

r2_knn_reg = r2_score(
    y_test,
    y_pred_knn_reg
)

print("MAE :", mae_knn_reg)
print("MSE :", mse_knn_reg)
print("RMSE:", rmse_knn_reg)
print("R²  :", r2_knn_reg)

MAE : 250979.8525
MSE : 88756220387.3515
RMSE: 297919.82207861147
R²  : -0.187772299271328

In [24]:
results.append({
    "Model": "KNN Regression",
    "MAE": mae_knn_reg,
    "MSE": mse_knn_reg,
    "RMSE": rmse_knn_reg,
    "R²": r2_knn_reg
})

In [25]:
# V. Decision Tree — Classification 

from sklearn.tree import DecisionTreeClassifier 

decision_tree_class_model = DecisionTreeClassifier(
    random_state=34
)

decision_tree_class_model.fit(
    X_train_class_processed,
    y_train_class
) 

y_pred_dt_class = decision_tree_class_model.predict(
    X_test_class_processed
)

In [26]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy_dt_class = accuracy_score(
    y_test_class,
    y_pred_dt_class
)

print("Accuracy:", accuracy_dt_class)

print("\nClassification Report:")
print(classification_report(
    y_test_class,
    y_pred_dt_class
))

print("\nConfusion Matrix:")
print(confusion_matrix(
    y_test_class,
    y_pred_dt_class
))

Accuracy: 0.5275

Classification Report:
              precision    recall  f1-score   support

  High Price       0.53      0.57      0.55       200
   Low Price       0.53      0.48      0.51       200

    accuracy                           0.53       400
   macro avg       0.53      0.53      0.53       400
weighted avg       0.53      0.53      0.53       400


Confusion Matrix:
[[114  86]
 [103  97]]

In [27]:
classification_results.append({
    "Model": "Decision Tree Classification",
    "Accuracy": accuracy_dt_class
})

In [28]:
# VI. Decision Tree — Regression 

from sklearn.tree import DecisionTreeRegressor 

decision_tree_reg_model = DecisionTreeRegressor(
    random_state=34
)

decision_tree_reg_model.fit(
    X_train_processed,
    y_train
) 

y_pred_dt_reg = decision_tree_reg_model.predict(
    X_test_processed
)

In [29]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae_dt_reg = mean_absolute_error(
    y_test,
    y_pred_dt_reg
)

mse_dt_reg = mean_squared_error(
    y_test,
    y_pred_dt_reg
)

rmse_dt_reg = np.sqrt(mse_dt_reg)

r2_dt_reg = r2_score(
    y_test,
    y_pred_dt_reg
)

print("MAE :", mae_dt_reg)
print("MSE :", mse_dt_reg)
print("RMSE:", rmse_dt_reg)
print("R²  :", r2_dt_reg)

MAE : 318538.565
MSE : 150323621880.645
RMSE: 387715.90356941125
R²  : -1.0116926252237337

In [30]:
results.append({
    "Model": "Decision Tree Regression",
    "MAE": mae_dt_reg,
    "MSE": mse_dt_reg,
    "RMSE": rmse_dt_reg,
    "R²": r2_dt_reg
})

In [31]:
# VII. SVM — Classification 

from sklearn.svm import SVC 

svm_class_model = SVC(
    kernel="rbf",
    random_state=34
)

svm_class_model.fit(
    X_train_class_processed,
    y_train_class
)

y_pred_svm_class = svm_class_model.predict(
    X_test_class_processed
)

In [32]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy_svm_class = accuracy_score(
    y_test_class,
    y_pred_svm_class
)

print("Accuracy:", accuracy_svm_class)

print("\nClassification Report:")
print(classification_report(
    y_test_class,
    y_pred_svm_class
))

print("\nConfusion Matrix:")
print(confusion_matrix(
    y_test_class,
    y_pred_svm_class
))

Accuracy: 0.5275

Classification Report:
              precision    recall  f1-score   support

  High Price       0.52      0.58      0.55       200
   Low Price       0.53      0.47      0.50       200

    accuracy                           0.53       400
   macro avg       0.53      0.53      0.53       400
weighted avg       0.53      0.53      0.53       400


Confusion Matrix:
[[116  84]
 [105  95]]

In [33]:
classification_results.append({
    "Model": "SVM Classification",
    "Accuracy": accuracy_svm_class
})

In [34]:
# VIII. SVM — Regression 

from sklearn.svm import SVR 

svm_reg_model = SVR(
    kernel="rbf"
)

svm_reg_model.fit(
    X_train_processed,
    y_train
) 

y_pred_svm_reg = svm_reg_model.predict(
    X_test_processed
)

In [35]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae_svm_reg = mean_absolute_error(
    y_test,
    y_pred_svm_reg
)

mse_svm_reg = mean_squared_error(
    y_test,
    y_pred_svm_reg
)

rmse_svm_reg = np.sqrt(mse_svm_reg)

r2_svm_reg = r2_score(
    y_test,
    y_pred_svm_reg
)

print("MAE :", mae_svm_reg)
print("MSE :", mse_svm_reg)
print("RMSE:", rmse_svm_reg)
print("R²  :", r2_svm_reg)

MAE : 234452.36484567993
MSE : 74811702723.76428
RMSE: 273517.28048473335
R²  : -0.001161020250832312

In [36]:
results.append({
    "Model": "SVM Regression",
    "MAE": mae_svm_reg,
    "MSE": mse_svm_reg,
    "RMSE": rmse_svm_reg,
    "R²": r2_svm_reg
})

In [37]:
# IX. Bagging 

from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor 

bagging_reg_model = BaggingRegressor(
    estimator=DecisionTreeRegressor(random_state=34),
    n_estimators=100,
    random_state=34
)

bagging_reg_model.fit(
    X_train_processed,
    y_train
) 

y_pred_bagging_reg = bagging_reg_model.predict(
    X_test_processed
)

In [38]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae_bagging_reg = mean_absolute_error(
    y_test,
    y_pred_bagging_reg
)

mse_bagging_reg = mean_squared_error(
    y_test,
    y_pred_bagging_reg
)

rmse_bagging_reg = np.sqrt(mse_bagging_reg)

r2_bagging_reg = r2_score(
    y_test,
    y_pred_bagging_reg
)

print("MAE :", mae_bagging_reg)
print("MSE :", mse_bagging_reg)
print("RMSE:", rmse_bagging_reg)
print("R²  :", r2_bagging_reg)

MAE : 239197.85909999997
MSE : 78316142544.5256
RMSE: 279850.21448004217
R²  : -0.04805887738577708

In [39]:
results.append({
    "Model": "Bagging Regression",
    "MAE": mae_bagging_reg,
    "MSE": mse_bagging_reg,
    "RMSE": rmse_bagging_reg,
    "R²": r2_bagging_reg
})

In [40]:
# X. Random Forest — Classification 

from sklearn.ensemble import RandomForestClassifier 

random_forest_class_model = RandomForestClassifier(
    n_estimators=100,
    random_state=34
)

random_forest_class_model.fit(
    X_train_class_processed,
    y_train_class
) 

y_pred_rf_class = random_forest_class_model.predict(
    X_test_class_processed
)

In [41]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy_rf_class = accuracy_score(
    y_test_class,
    y_pred_rf_class
)

print("Accuracy:", accuracy_rf_class)

print("\nClassification Report:")
print(classification_report(
    y_test_class,
    y_pred_rf_class
))

print("\nConfusion Matrix:")
print(confusion_matrix(
    y_test_class,
    y_pred_rf_class
))

Accuracy: 0.5075

Classification Report:
              precision    recall  f1-score   support

  High Price       0.51      0.54      0.52       200
   Low Price       0.51      0.48      0.49       200

    accuracy                           0.51       400
   macro avg       0.51      0.51      0.51       400
weighted avg       0.51      0.51      0.51       400


Confusion Matrix:
[[107  93]
 [104  96]]

In [42]:
classification_results.append({
    "Model": "Random Forest Classification",
    "Accuracy": accuracy_rf_class
})

In [43]:
# XI. Random Forest — Regression 

from sklearn.ensemble import RandomForestRegressor 

random_forest_reg_model = RandomForestRegressor(
    n_estimators=100,
    random_state=34
)

random_forest_reg_model.fit(
    X_train_processed,
    y_train
) 

y_pred_rf_reg = random_forest_reg_model.predict(
    X_test_processed
)

In [44]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae_rf_reg = mean_absolute_error(
    y_test,
    y_pred_rf_reg
)

mse_rf_reg = mean_squared_error(
    y_test,
    y_pred_rf_reg
)

rmse_rf_reg = np.sqrt(mse_rf_reg)

r2_rf_reg = r2_score(
    y_test,
    y_pred_rf_reg
)

print("MAE :", mae_rf_reg)
print("MSE :", mse_rf_reg)
print("RMSE:", rmse_rf_reg)
print("R²  :", r2_rf_reg)

MAE : 239339.18475000001
MSE : 78523531517.67662
RMSE: 280220.50516990473
R²  : -0.050834242046507994

In [45]:
results.append({
    "Model": "Random Forest Regression",
    "MAE": mae_rf_reg,
    "MSE": mse_rf_reg,
    "RMSE": rmse_rf_reg,
    "R²": r2_rf_reg
})

In [46]:
# XII. Gradient Boosting — Regression 

from sklearn.ensemble import GradientBoostingRegressor  

gradient_boosting_reg_model = GradientBoostingRegressor(
    n_estimators=100,
    random_state=34
)

gradient_boosting_reg_model.fit(
    X_train_processed,
    y_train
) 

y_pred_gb_reg = gradient_boosting_reg_model.predict(
    X_test_processed
)

In [47]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae_gb_reg = mean_absolute_error(
    y_test,
    y_pred_gb_reg
)

mse_gb_reg = mean_squared_error(
    y_test,
    y_pred_gb_reg
)

rmse_gb_reg = np.sqrt(mse_gb_reg)

r2_gb_reg = r2_score(
    y_test,
    y_pred_gb_reg
)

print("MAE :", mae_gb_reg)
print("MSE :", mse_gb_reg)
print("RMSE:", rmse_gb_reg)
print("R²  :", r2_gb_reg)

MAE : 238774.2035392326
MSE : 76938788653.24472
RMSE: 277378.4213907865
R²  : -0.029626560290510806

In [48]:
results.append({
    "Model": "Gradient Boosting Regression",
    "MAE": mae_gb_reg,
    "MSE": mse_gb_reg,
    "RMSE": rmse_gb_reg,
    "R²": r2_gb_reg
})

In [49]:
# XIII. Gradient Boosting — Classification 

from sklearn.ensemble import GradientBoostingClassifier 

gradient_boosting_class_model = GradientBoostingClassifier(
    n_estimators=100,
    random_state=34
)

gradient_boosting_class_model.fit(
    X_train_class_processed,
    y_train_class
) 

y_pred_gb_class = gradient_boosting_class_model.predict(
    X_test_class_processed
)

In [50]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy_gb_class = accuracy_score(
    y_test_class,
    y_pred_gb_class
)

print("Accuracy:", accuracy_gb_class)

print("\nClassification Report:")
print(classification_report(
    y_test_class,
    y_pred_gb_class
))

print("\nConfusion Matrix:")
print(confusion_matrix(
    y_test_class,
    y_pred_gb_class
))

Accuracy: 0.52

Classification Report:
              precision    recall  f1-score   support

  High Price       0.52      0.53      0.52       200
   Low Price       0.52      0.52      0.52       200

    accuracy                           0.52       400
   macro avg       0.52      0.52      0.52       400
weighted avg       0.52      0.52      0.52       400


Confusion Matrix:
[[105  95]
 [ 97 103]]

In [51]:
classification_results.append({
    "Model": "Gradient Boosting Classification",
    "Accuracy": accuracy_gb_class
})

In [52]:
# XIV. AdaBoost — Regression  

from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor 

adaboost_reg_model = AdaBoostRegressor(
    estimator=DecisionTreeRegressor(
        max_depth=3,
        random_state=34
    ),
    n_estimators=100,
    random_state=34
)

adaboost_reg_model.fit(
    X_train_processed,
    y_train
) 

y_pred_adaboost_reg = adaboost_reg_model.predict(
    X_test_processed
)

In [53]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae_adaboost_reg = mean_absolute_error(
    y_test,
    y_pred_adaboost_reg
)

mse_adaboost_reg = mean_squared_error(
    y_test,
    y_pred_adaboost_reg
)

rmse_adaboost_reg = np.sqrt(mse_adaboost_reg)

r2_adaboost_reg = r2_score(
    y_test,
    y_pred_adaboost_reg
)

print("MAE :", mae_adaboost_reg)
print("MSE :", mse_adaboost_reg)
print("RMSE:", rmse_adaboost_reg)
print("R²  :", r2_adaboost_reg)

MAE : 233995.93962488382
MSE : 74549477987.17291
RMSE: 273037.5028950655
R²  : 0.002348179182713128

In [54]:
results.append({
    "Model": "AdaBoost Regression",
    "MAE": mae_adaboost_reg,
    "MSE": mse_adaboost_reg,
    "RMSE": rmse_adaboost_reg,
    "R²": r2_adaboost_reg
})

In [55]:
# XV. AdaBoost — Classification 

from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier 

adaboost_class_model = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(
        max_depth=1,
        random_state=34
    ),
    n_estimators=100,
    random_state=34
)

adaboost_class_model.fit(
    X_train_class_processed,
    y_train_class
) 

y_pred_adaboost_class = adaboost_class_model.predict(
    X_test_class_processed
)

In [56]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy_adaboost_class = accuracy_score(
    y_test_class,
    y_pred_adaboost_class
)

print("Accuracy:", accuracy_adaboost_class)

print("\nClassification Report:")
print(classification_report(
    y_test_class,
    y_pred_adaboost_class
))

print("\nConfusion Matrix:")
print(confusion_matrix(
    y_test_class,
    y_pred_adaboost_class
))

Accuracy: 0.495

Classification Report:
              precision    recall  f1-score   support

  High Price       0.50      0.52      0.51       200
   Low Price       0.49      0.47      0.48       200

    accuracy                           0.49       400
   macro avg       0.49      0.49      0.49       400
weighted avg       0.49      0.49      0.49       400


Confusion Matrix:
[[104  96]
 [106  94]]

In [57]:
classification_results.append({
    "Model": "AdaBoost Classification",
    "Accuracy": accuracy_adaboost_class
})

In [58]:
import pandas as pd

regression_results_df = pd.DataFrame(results).sort_values("R²",ascending=False)

regression_results_df

,Model,MAE,MSE,RMSE,R²
7,AdaBoost Regression,233995.939625,7.454948e+10,273037.502895,0.002348
0,Linear Regression,234637.112976,7.464483e+10,273212.064213,0.001072
3,SVM Regression,234452.364846,7.481170e+10,273517.280485,-0.001161
6,Gradient Boosting Regression,238774.203539,7.693879e+10,277378.421391,-0.029627
4,Bagging Regression,239197.859100,7.831614e+10,279850.214480,-0.048059
5,Random Forest Regression,239339.184750,7.852353e+10,280220.505170,-0.050834
1,KNN Regression,250979.852500,8.875622e+10,297919.822079,-0.187772
2,Decision Tree Regression,318538.565000,1.503236e+11,387715.903569,-1.011693

In [59]:
classification_results_df = pd.DataFrame(classification_results).sort_values("Accuracy", ascending = False)

classification_results_df

                              Model  Accuracy
1                KNN Classification    0.5325
0               Logistic Regression    0.5300
2      Decision Tree Classification    0.5275
3                SVM Classification    0.5275
5  Gradient Boosting Classification    0.5200
4      Random Forest Classification    0.5075
6           AdaBoost Classification    0.4950