In [1]:
# pandas functions

# (1.) pd.DataFrame = creates a 2D table with rows and columns

import pandas as pd

data = {
    "Names" : ["Ramesh", "Raghu", "Vikram"],
    "Age": [22, 21, 19] 
}
df = pd.DataFrame(data) 
print(df)
   
"""
corner cases:- 

All columns should have the same number of values.
Missing values become NaN.
Data can come from dictionaries, lists, NumPy arrays, or other DataFrames.

"""

    Names  Age
0  Ramesh   22
1   Raghu   21
2  Vikram   19

'\ncorner cases:- \n\nAll columns should have the same number of values.\nMissing values become NaN.\nData can come from dictionaries, lists, NumPy arrays, or other DataFrames.\n\n'

In [11]:
# (2.) pd.Series() = create 1dimensional labeled array. 

import numpy as np

B = pd.Series([1, 2, 3, 4, 5]) 

print(B)

print("----------------------------------------")

s = pd.Series([10,20,30], index=["A","B","C"])

print(s)

"""" 
Corner Cases:-

Supports custom indexes.
Can store numbers, strings, or mixed data types.
"""

0    1
1    2
2    3
3    4
4    5
dtype: int64
----------------------------------------
A    10
B    20
C    30
dtype: int64

'" \nCorner Cases:-\n\nSupports custom indexes.\nCan store numbers, strings, or mixed data types.\n'

In [12]:
# (3.) pd.read_csv() :- Reads a CSV file into a DataFrame. 

df = pd.read_csv("Student_Details.csv", delimiter = ",")

print(df)

   Student_ID    Name  Age            Course  Marks       City
0         101  Ramesh   23            Python     92  Hyderabad
1         102   Priya   21              Java     88  Bangalore
2         103   Rahul   24      Data Science     95    Chennai
3         104  Anjali   22                AI     90       Pune
4         105   Kiran   23  Machine Learning     85     Mumbai

In [ ]:
# (4.) pd.concat() = Combines two or more DataFrames or Series.

df1 = pd.DataFrame({"A":[1,2]})
df2 = pd.DataFrame({"A":[3,4]})

print(pd.concat([df1,df2]))

print("-------------------------------------") 

# ignore index 

pd.concat([df1, df2], ignore_index=True)

""" Corner Cases :-

Default keeps original indexes.
Can concatenate rows (axis=0) or columns (axis=1). 
"""

   A
0  1
1  2
0  3
1  4
-------------------------------------

   A
0  1
1  2
2  3
3  4

In [ ]:
# (5.) pd.date_range() = Creates a sequence of dates.

dates = pd.date_range("2026-08-06", periods = 5)

print(dates)

""" Corner Cases :-
Frequency defaults to daily.
Use freq="M" for monthly, "Y" for yearly, "H" for hourly."""

DatetimeIndex(['2026-08-06', '2026-08-07', '2026-08-08', '2026-08-09',
               '2026-08-10'],
              dtype='datetime64[us]', freq='D')

In [ ]:
# (6.) pd.to_datetime() = Converts data into datetime format.

dates = pd.to_datetime(["2026-08-07", "2026-09-10"])

print(dates)

"""  Corner Cases:- 
Invalid dates raise errors unless errors="coerce" is used.
Invalid values become NaT (Not a Time)."""

DatetimeIndex(['2026-08-07', '2026-09-10'], dtype='datetime64[us]', freq=None)

In [19]:
# (7.) pd.to_numeric() = Converts values into numeric data types. 

s = pd.Series(["10", "20", '30']) 
print(pd.to_numeric(s))

print("------------------------------------------------")
# Invalid values become NaN.

s = pd.Series(["Ramesh", "20", '30']) 

pd.to_numeric(s, errors="coerce")

0    10
1    20
2    30
dtype: int64
------------------------------------------------

0     NaN
1    20.0
2    30.0
dtype: float64

In [ ]:
# (8.) pd.get_dummies() = Converts categorical values into dummy (one-hot encoded) columns.

df = pd.DataFrame(
    {
        "color": ["blue", "red", "blue"]
    }
)
print(pd.get_dummies(df))

"""  
Corner Cases:-
Widely used in Machine Learning.
Creates one column for each unique category.
"""

   color_blue  color_red
0        True      False
1       False       True
2        True      False

In [23]:
# (9.) pd.Categorical() = Creates categorical data with fixed categories.

categorical_data = pd.Categorical(["orange", "apple", "banana","orange", "apple"])

print(categorical_data)

"""  Corner Cases:-
Saves memory for repeated values.
Useful for ordered categories.
"""

pd.Categorical(
    ["Low","Medium","High"],
    ordered=True
)

['orange', 'apple', 'banana', 'orange', 'apple']
Categories (3, str): ['apple', 'banana', 'orange']

['Low', 'Medium', 'High']
Categories (3, str): ['High' < 'Low' < 'Medium']

In [28]:
# 10. pd.set_option() = Changes Pandas display or behavior settings.

pd.set_option("display.max_columns", None) # Now Pandas displays all columns.
pd.set_option("display.max_rows", 100)

""" Corner Cases

Common options:

display.max_rows
display.max_columns
display.width
display.precision """

# Reset option: 

pd.reset_option("display.max_rows")

In [13]:
# (11.) head():- Returns the first n rows of a DataFrame.

data = pd.read_excel("Student_Details_.xlsx") 

print(data.head())

print("------------------------------------------") 

print(data.head(2))

""" Default returns 5 rows.
If n is larger than the number of rows, it returns the entire DataFrame. """

   Student_ID    Name  Age Department  Marks       City
0         101  Ramesh   22        CSE     85  Hyderabad
1         102   Priya   21        ECE     91  Bengaluru
2         103   Rahul   23       MECH     76    Chennai
3         104   Anita   22        CSE     88     Mumbai
4         105   Kiran   20        EEE     69       Pune
------------------------------------------
   Student_ID    Name  Age Department  Marks       City
0         101  Ramesh   22        CSE     85  Hyderabad
1         102   Priya   21        ECE     91  Bengaluru

' Default returns 5 rows.\nIf n is larger than the number of rows, it returns the entire DataFrame. '

In [ ]:
# (12.) tail():- Returns the last n rows of a DataFrame.

print(data.tail())

print("-------------------------------")

print(data.tail(2))

"""  Corner Cases:-
Default returns 5 rows.
Useful for checking recently added data. """

   Student_ID    Name  Age Department  Marks       City
5         106   Sneha   21        CSE     95  Hyderabad
6         107   Arjun   22        ECE     81      Delhi
7         108   Divya   23         IT     73    Kolkata
8         109  Vikram   21         IT     89    Chennai
9         110    Neha   20       MECH     92  Hyderabad
-------------------------------
   Student_ID    Name  Age Department  Marks       City
8         109  Vikram   21         IT     89    Chennai
9         110    Neha   20       MECH     92  Hyderabad

In [ ]:
# 13. info() = Displays summary information about a DataFrame.

data.info()

""" Corner Cases:-

Shows:

Number of rows
Number of columns
Data types
Memory usage
Null values

Very useful before data cleaning.  """

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Marks       10 non-null     int64
 5   City        10 non-null     str
dtypes: int64(3), str(3)
memory usage: 765.0 bytes

In [ ]:
# (14.) describe() = Generates statistical summary of numeric columns. 

data.describe()

""" Corner Cases:- 
Works only on numeric columns by default.
For object columns: df.describe(include="object")
For all columns: df.describe(include="all")
"""

       Student_ID        Age      Marks
count    10.00000  10.000000  10.000000
mean    105.50000  21.500000  83.900000
std       3.02765   1.080123   8.786985
min     101.00000  20.000000  69.000000
25%     103.25000  21.000000  77.250000
50%     105.50000  21.500000  86.500000
75%     107.75000  22.000000  90.500000
max     110.00000  23.000000  95.000000

In [ ]:
# 15. mean() = Calculates the average of numeric values.

data["Marks"].mean()

print("-----------------------------------")

data["Age"].mean()

""" Corner Cases
Ignores NaN values by default.
Works only on numeric columns."""

-----------------------------------

np.float64(21.5)

In [49]:
# 16. median(): Returns the middle value after sorting the data.

data["Age"].median()

np.float64(21.5)

In [55]:
# (17.) sum() = Adds all values together.

data["Marks"].sum() #839

print("--------------------------------------------")
# Column-wise Sum 

data.sum(numeric_only=True)

--------------------------------------------

Student_ID    1055
Age            215
Marks          839
dtype: int64

In [9]:
# (18.) value_counts() = Counts how many times each unique value appears.

data = pd.read_excel("Student_Details_.xlsx")

data["Marks"].value_counts()


# Include missing values: Useful for frequency analysis.

data["Marks"].value_counts(dropna=False)

Marks
85    1
91    1
76    1
88    1
69    1
95    1
81    1
73    1
89    1
92    1
Name: count, dtype: int64

In [14]:
# 19. groupby() = Groups data based on one or more columns for analysis.

data.groupby("Age")["Marks"].mean()

""" 
Corner Cases
Returns a GroupBy object until an aggregation (sum(), mean(), etc.) is applied.
Can group by multiple columns. """

data.groupby("Age")["Marks"].agg(["mean","max","min"])

          mean  max  min
Age
20   80.500000   92   69
21   91.666667   95   89
22   84.666667   88   81
23   74.500000   76   73

In [15]:
# 20. sort_values() = Sorts rows based on one or more columns.

# default = ascending 

print(data.sort_values("Marks"))

print("---------------------------------------")

# DESCENDING 

print(data.sort_values("Marks", ascending=False))

print("--------------------------------------")

# For multiple coplumns 

data.sort_values(["Age","Marks"])

# Original DataFrame remains unchanged unless: we add parameter inplace=True

   Student_ID    Name  Age Department  Marks       City
4         105   Kiran   20        EEE     69       Pune
7         108   Divya   23         IT     73    Kolkata
2         103   Rahul   23       MECH     76    Chennai
6         107   Arjun   22        ECE     81      Delhi
0         101  Ramesh   22        CSE     85  Hyderabad
3         104   Anita   22        CSE     88     Mumbai
8         109  Vikram   21         IT     89    Chennai
1         102   Priya   21        ECE     91  Bengaluru
9         110    Neha   20       MECH     92  Hyderabad
5         106   Sneha   21        CSE     95  Hyderabad
---------------------------------------
   Student_ID    Name  Age Department  Marks       City
5         106   Sneha   21        CSE     95  Hyderabad
9         110    Neha   20       MECH     92  Hyderabad
1         102   Priya   21        ECE     91  Bengaluru
8         109  Vikram   21         IT     89    Chennai
3         104   Anita   22        CSE     88     Mumbai
0         101  Ramesh   22        CSE     85  Hyderabad
6         107   Arjun   22        ECE     81      Delhi
2         103   Rahul   23       MECH     76    Chennai
7         108   Divya   23         IT     73    Kolkata
4         105   Kiran   20        EEE     69       Pune
--------------------------------------

   Student_ID    Name  Age Department  Marks       City
4         105   Kiran   20        EEE     69       Pune
9         110    Neha   20       MECH     92  Hyderabad
8         109  Vikram   21         IT     89    Chennai
1         102   Priya   21        ECE     91  Bengaluru
5         106   Sneha   21        CSE     95  Hyderabad
6         107   Arjun   22        ECE     81      Delhi
0         101  Ramesh   22        CSE     85  Hyderabad
3         104   Anita   22        CSE     88     Mumbai
7         108   Divya   23         IT     73    Kolkata
2         103   Rahul   23       MECH     76    Chennai

In [18]:
# 21. drop() = Removes specified rows or columns from a DataFrame.

print(data.drop("Age", axis=1)) # column drop 
print(data.drop(5)) # Row drop    (Removes the row with index 5.)

"""   Corner Cases
axis=0 → Drop rows (default)
axis=1 → Drop columns
Original DataFrame is unchanged unless inplace=True."""

   Student_ID    Name Department  Marks       City
0         101  Ramesh        CSE     85  Hyderabad
1         102   Priya        ECE     91  Bengaluru
2         103   Rahul       MECH     76    Chennai
3         104   Anita        CSE     88     Mumbai
4         105   Kiran        EEE     69       Pune
5         106   Sneha        CSE     95  Hyderabad
6         107   Arjun        ECE     81      Delhi
7         108   Divya         IT     73    Kolkata
8         109  Vikram         IT     89    Chennai
9         110    Neha       MECH     92  Hyderabad
   Student_ID    Name  Age Department  Marks       City
0         101  Ramesh   22        CSE     85  Hyderabad
1         102   Priya   21        ECE     91  Bengaluru
2         103   Rahul   23       MECH     76    Chennai
3         104   Anita   22        CSE     88     Mumbai
4         105   Kiran   20        EEE     69       Pune
6         107   Arjun   22        ECE     81      Delhi
7         108   Divya   23         IT     73    Kolkata
8         109  Vikram   21         IT     89    Chennai
9         110    Neha   20       MECH     92  Hyderabad

'   Corner Cases\naxis=0 → Drop rows (default)\naxis=1 → Drop columns\nOriginal DataFrame is unchanged unless inplace=True.'

In [ ]:
# 22. dropna() = Removes rows or columns containing missing (NaN) values.

df.dropna() #Rows containing NaN values are removed.
df.dropna(axis=1) #Remove Columns with NaN

"""Corner Cases
Default removes rows.
Use how="all" to remove rows only if all values are missing.
Use thresh= to specify the minimum number of non-null values required."""

  color
0  blue
1   red
2  blue

In [ ]:
# 23. 23. fillna() = Replaces missing (NaN) values with a specified value.

df.fillna(0)   # All NaN values become 0. 

df["Marks"] = df["Marks"].fillna(df["Marks"].mean()) # Fill with Mean 

""" Corner Cases
Common replacements:
0
Mean
Median
Mode
Can use forward fill (ffill) or backward fill (bfill).
"""

In [ ]:
# 24. isnull() = Checks whether values are missing (NaN).

df.isnull()    # Returns True for missing values, False otherwise.

# To Count Missing Values, df.isnull().sum()

   color
0  False
1  False
2  False

In [ ]:
# 25. duplicated() = Identifies duplicate rows.

df.duplicated()

"""Corner Cases
First occurrence is not marked as duplicate.
Returns a Boolean Series."""

0    False
1    False
2     True
dtype: bool

In [ ]:
# 26. drop_duplicates() = Removes duplicate rows.

df.drop_duplicates() # Duplicate rows are removed.

# df.drop_duplicates(subset="Name") # Remove Based on One Column

"""Corner Cases
Keeps the first occurrence by default.
Use keep="last" to keep the last occurrence.
Original DataFrame remains unchanged unless inplace=True."""

  color
0  blue
1   red

In [87]:
# 27. reset_index() = Resets the DataFrame index to the default integer index.

df.reset_index()

# To remove old index values ( df.reset_index(drop=True) )

   index color
0      0  blue
1      1   red
2      2  blue

In [90]:
# 28. set_index() = Sets a column as the DataFrame index.

data.set_index("Student_ID") # Student_ID becomes the row index.

              Name  Age Department  Marks       City
Student_ID
101         Ramesh   22        CSE     85  Hyderabad
102          Priya   21        ECE     91  Bengaluru
103          Rahul   23       MECH     76    Chennai
104          Anita   22        CSE     88     Mumbai
105          Kiran   20        EEE     69       Pune
106          Sneha   21        CSE     95  Hyderabad
107          Arjun   22        ECE     81      Delhi
108          Divya   23         IT     73    Kolkata
109         Vikram   21         IT     89    Chennai
110           Neha   20       MECH     92  Hyderabad

In [14]:
# 29. astype() = Changes the data type of a column.

data["Age"] = data["Age"].astype(float) # Age column becomes float.

# Convert Multiple Columns
data.astype({
    "Age": int,
    "Marks": float
})

print(df[["Marks","Age"]])    # to select multiple columns at atime.

   Marks  Age
0     92   23
1     88   21
2     95   24
3     90   22
4     85   23

In [16]:
# 30. select_dtypes() = Selects columns based on their data types.

df.select_dtypes(include="number")

print(df.select_dtypes(int))
print("---------------------------")
print(df.select_dtypes(str))

# Select Object Columns df.select_dtypes(include="object")

# include="number"
# include="object"
# include="datetime"
# exclude="number"

   Student_ID  Age  Marks
0         101   23     92
1         102   21     88
2         103   24     95
3         104   22     90
4         105   23     85
---------------------------
     Name            Course       City
0  Ramesh            Python  Hyderabad
1   Priya              Java  Bangalore
2   Rahul      Data Science    Chennai
3  Anjali                AI       Pune
4   Kiran  Machine Learning     Mumbai

In [ ]:
# (31.) loc[] = loc[] is used to select rows and columns by their labels/names.        loc → label-based selection.

print(df.loc[2])             # Selects the row whose index label is 2.
print("--------------------------------")
print(df.loc[[1,3,0]])         # Selects the rows whose index label is 1,3,0.
print("--------------------------------")
print(df.loc[1:5, ["Name", "Marks"]])                    #Rows    → 1 to 5,            Columns → Name, Marks 
print("---------------------------------")

# Updating values => loc is also very useful for modifying specific data:
 
df.loc[df["Marks"] > 90, "Result"] = "A+"
print(df[["Marks","Result"]])

# corner cases
# (1.) df.loc[20],       selects the row with index label 20, It does NOT mean "20th row".
# (2.) df.loc[1:5],      selects 1, 2, 3, 4, 5.   This differs from normal Python slicing.
# df.loc[100]             If index 100 doesn't exist, you'll get a KeyError.

Student_ID             103
Name                 Rahul
Age                     24
Course        Data Science
Marks                   95
City               Chennai
Result                  A+
Name: 2, dtype: object
--------------------------------
   Student_ID    Name  Age  Course  Marks       City Result
1         102   Priya   21    Java     88  Bangalore    NaN
3         104  Anjali   22      AI     90       Pune    NaN
0         101  Ramesh   23  Python     92  Hyderabad     A+
--------------------------------
     Name  Marks
1   Priya     88
2   Rahul     95
3  Anjali     90
4   Kiran     85
---------------------------------
   Marks Result
0     92     A+
1     88    NaN
2     95     A+
3     90    NaN
4     85    NaN

In [36]:
# (32.) iloc[] = iloc[] selects rows and columns using their integer positions.                     iloc → integer-location based selection

print(df.iloc[0])                # selects the first row, regardless of its index label.
print("---------------------------------")
print(df.iloc[[0, 2]])             # First row, Third row
print("---------------------------------")

# Select rows and columns

print(df.iloc[0:3, 0:2])                 # Rows    → positions 0, 1, 2   &  Columns → positions 0, 1       ⚠️ Here Python-style slicing applies, so the ending position is excluded.
print("---------------------------------")
print(df.iloc[2, 1])                      # 3rd row, 2nd column

Student_ID          101
Name             Ramesh
Age                  23
Course           Python
Marks                92
City          Hyderabad
Result               A+
Name: 0, dtype: object
---------------------------------
   Student_ID    Name  Age        Course  Marks       City Result
0         101  Ramesh   23        Python     92  Hyderabad     A+
2         103   Rahul   24  Data Science     95    Chennai     A+
---------------------------------
   Student_ID    Name
0         101  Ramesh
1         102   Priya
2         103   Rahul
---------------------------------
Rahul

In [ ]:
# (33.) df.shape  = It returns the shape of dataframe                 
df.shape          # don't use (), cause it is not an attribute,not a function.

(5, 7)

In [ ]:
# (34.) corr() = corr() calculates the correlation between numerical variables. To understand whether two variables have a linear relationship.

# corelation ranges from -1 → +1

df.corr(numeric_only=True)     # ( +1 = positive relation ; )
                               # ( -1 = negative relation ; negative relation b/w Student_ID, Marks)
                               # ( 0 = No relation )

            Student_ID       Age     Marks
Student_ID    1.000000  0.138675 -0.498273
Age           0.138675  1.000000  0.518235
Marks        -0.498273  0.518235  1.000000

In [26]:
# (35.) sample() = Pandas return some random rows from data frame.

df = pd.read_csv("Student_Details.csv")
print(df.sample(5))

# we can use                df.sample(frac=0.2) means, This randomly selects 20% of the rows.

# ML Use:                   Randomly inspect data, Create random samples, Exploratory Data Analysis, Sampling datasets

# Important

df.sample(n=5, random_state=42)        #   random_state makes the random selection reproducible.

   Student_ID    Name  Age            Course  Marks       City
1         102   Priya   21              Java     88  Bangalore
2         103   Rahul   24      Data Science     95    Chennai
0         101  Ramesh   23            Python     92  Hyderabad
3         104  Anjali   22                AI     90       Pune
4         105   Kiran   23  Machine Learning     85     Mumbai

   Student_ID    Name  Age            Course  Marks       City
1         102   Priya   21              Java     88  Bangalore
4         105   Kiran   23  Machine Learning     85     Mumbai
2         103   Rahul   24      Data Science     95    Chennai
0         101  Ramesh   23            Python     92  Hyderabad
3         104  Anjali   22                AI     90       Pune

In [ ]:
# (36.) query() = Filters rows using a condition written as a string.

print(df["Marks"].head())

print("------------------------------------------------")

print(df.query("Marks > 85"))

print("------------------------------------------------")

# Multiple conditions ( Using and, or)

print(df.query("Marks > 80 and Age < 22"))

# ML Use: Filtering training data, Exploratory analysis, Selecting records based on conditions, Creating subsets of datasets

# simply,               df.query("Marks > 80")              same as            df[df["Marks"] > 80]

0    92
1    88
2    95
3    90
4    85
Name: Marks, dtype: int64
------------------------------------------------
   Student_ID    Name  Age        Course  Marks       City
0         101  Ramesh   23        Python     92  Hyderabad
1         102   Priya   21          Java     88  Bangalore
2         103   Rahul   24  Data Science     95    Chennai
3         104  Anjali   22            AI     90       Pune
------------------------------------------------
   Student_ID   Name  Age Course  Marks       City
1         102  Priya   21   Java     88  Bangalore

In [ ]:
# (37.)  between() = Checks whether values fall within a specified range.

df["Marks"].between(80, 90)   

# same as df[df["Marks"].between(60, 80)]

"""" ML Use:
Filtering age ranges
Filtering salary ranges
Selecting valid numerical ranges
Data validation """

0    False
1     True
2    False
3     True
4     True
Name: Marks, dtype: bool

In [ ]:
# (38.) clip() = Limits values to a specified minimum and maximum boundary. 

df["Marks"] 
print("-----------------------------------")

df["Marks"].clip(lower=80, upper=90)              # Values below 80 become 80. Values above 90 become 90.

"""ML Use:
Handling extreme values
Limiting outliers
Data preprocessing
Preventing unrealistic values"""

-----------------------------------

0    90
1    88
2    90
3    90
4    85
Name: Marks, dtype: int64

In [43]:
# (39.)   where() =  Keeps values that satisfy a condition and replaces values that don't.

print(df ["Marks"])

df["Marks"].where(df["Marks"] > 85)

0    92
1    88
2    95
3    90
4    85
Name: Marks, dtype: int64

0    92.0
1    88.0
2    95.0
3    90.0
4     NaN
Name: Marks, dtype: float64

In [ ]:
# (40.)    map() = Maps each value in a Series to another value or applies a function.

import numpy as np
df = pd.read_csv("C:\Calibo_Course\ML_TASKS\student_dataset.csv")
print(df.head(3))

print("-----------------------------------------")

# (1.) Dictionary mapping

new_list = df["Gender"].map({
    "Male": 1,
    "Female": 0
})   
print(new_list.head())

print("------------------------------------------")

# (2.) Function mappig

new_marks_list = df["Marks"].map(lambda x: x + 5)         #lambda is useful here because it lets you define a small function directly inside apply() without separately creating a named function.
print(new_marks_list.head())

  StudentID      Branch  Gender  StudyHours  AttendancePercent  Marks
0      S001       Civil    Male         6.1               96.3   86.6
1      S002  Mechanical  Female         4.4               82.0   64.9
2      S003         EEE  Female         5.8               82.3   76.6
-----------------------------------------
0    1
1    0
2    0
3    1
4    0
Name: Gender, dtype: int64
------------------------------------------
0    91.6
1    69.9
2    81.6
3    69.5
4    96.3
Name: Marks, dtype: float64

In [ ]:
 # (41.) apply() = Applies a function to each row, column, or element, depending on how it is used.

# (1.) Series:

print(df["Age"].apply(lambda x: x - 5).head())     # Applies the function to each value/element. Each mark gets 5 subtracted.

print("-------------------------------------------")
# (2.) Column:

# df["Marks"].apply(lambda x: "Pass" if x >= 40 else "Fail").head()
print(df.apply(lambda col: col.max(), axis=0))

print("-------------------------------------------")

# (3.) Row

# df.apply(lambda row: row["EEE"] + row["Science"], axis=1)

0    17
1    16
2    14
Name: Age, dtype: int64
-------------------------------------------
Names    Vikram
Age          22
dtype: object
-------------------------------------------

KeyError: 'Maths'

In [27]:
# (42.) iterrows() = Iterates over DataFrame rows one at a time.

for index, row in df.iterrows():
    print(index, row["StudentID"], row["Marks"])

0 S001 86.6
1 S002 64.9
2 S003 76.6
3 S004 64.5
4 S005 91.3
5 S006 69.4
6 S007 70.1
7 S008 79.9
8 S009 82.8
9 S010 80.8
10 S011 84.4
11 S012 84.1
12 S013 83.2
13 S014 79.4
14 S015 70.5
15 S016 68.6
16 S017 43.4
17 S018 58.8
18 S019 73.7
19 S020 67.8
20 S021 87.1
21 S022 73.5
22 S023 85.0
23 S024 98.0
24 S025 68.3
25 S026 99.0
26 S027 68.3
27 S028 88.0
28 S029 66.6
29 S030 64.8
30 S031 82.0
31 S032 68.5
32 S033 99.4
33 S034 79.7
34 S035 65.2
35 S036 69.9
36 S037 71.3
37 S038 67.1
38 S039 88.0
39 S040 nan

In [ ]:
# (43.)  corr() = Calculates the correlation between numerical columns.
 
print(df.corr(numeric_only=True))
'''
+1  → Perfect positive correlation
 0  → No linear correlation
-1  → Perfect negative correlation
'''

                   StudyHours  AttendancePercent     Marks
StudyHours           1.000000           0.594219  0.741811
AttendancePercent    0.594219           1.000000  0.573369
Marks                0.741811           0.573369  1.000000

In [ ]:
# (44.) cumsum() = Calculates the cumulative sum of values. ()

df["Marks"].cumsum()   # with evey new value, previous value is added and provide new value. eg:  for 2nd element, 86.6 + 64.9 = 151.5

0       86.6
1      151.5
2      228.1
3      292.6
4      383.9
5      453.3
6      523.4
7      603.3
8      686.1
9      766.9
10     851.3
11     935.4
12    1018.6
13    1098.0
14    1168.5
15    1237.1
16    1280.5
17    1339.3
18    1413.0
19    1480.8
20    1567.9
21    1641.4
22    1726.4
23    1824.4
24    1892.7
25    1991.7
26    2060.0
27    2148.0
28    2214.6
29    2279.4
30    2361.4
31    2429.9
32    2529.3
33    2609.0
34    2674.2
35    2744.1
36    2815.4
37    2882.5
38    2970.5
39       NaN
Name: Marks, dtype: float64

In [44]:
# (45.) quantile() = returns the value at a specified percentile of the data. Mostly used to fine Q1 and Q3 
        # always input should be b/w 0 to 1. 25 percentile means 0.24, 60 percentile means 0.6

print(df["Marks"].quantile(0.25))
print(df["Age"].quantile(0.75))
print("------------------------------------------")
# 50% quantile(0.5) = median                  As, median is center, means at 0.5
print(df["Marks"].quantile(0.50))
print(df["Marks"].median())

88.0
23.0
------------------------------------------
90.0
90.0

In [47]:
# (46.) nlargest() = Returns the N rows with the largest values from a specified column.

print(df.nlargest(4,"Marks"))            # Given 4 largest values, from Marks column.

print("----------------------------------")

# If multiple rows have the same value, you can control how ties are handled using keep.

df.nlargest(3, "Marks", keep="all")

   Student_ID    Name  Age        Course  Marks       City Result
2         103   Rahul   24  Data Science     95    Chennai     A+
0         101  Ramesh   23        Python     92  Hyderabad     A+
3         104  Anjali   22            AI     90       Pune    NaN
1         102   Priya   21          Java     88  Bangalore    NaN
----------------------------------

   Student_ID    Name  Age        Course  Marks       City Result
2         103   Rahul   24  Data Science     95    Chennai     A+
0         101  Ramesh   23        Python     92  Hyderabad     A+
3         104  Anjali   22            AI     90       Pune    NaN

In [ ]:
# (47.) nsmallest() = Returns the N rows with the smallest values from a specified column.

print(df.nsmallest(3, "Marks"))

print("----------------------------------")

# Ties.                  df.nsmallest(3, "Marks", keep="all") , keeps all rows tied at the boundary.

   Student_ID    Name  Age            Course  Marks       City Result
4         105   Kiran   23  Machine Learning     85     Mumbai    NaN
1         102   Priya   21              Java     88  Bangalore    NaN
3         104  Anjali   22                AI     90       Pune    NaN
----------------------------------

In [51]:
# (48.) to_csv() = Converts/saves a DataFrame into a CSV file.

df.to_csv("students.csv", index=False)      # Always use, index = False, Because otherwise Pandas also saves the DataFrame index as an additional column.

In [ ]:
# (49.) to_excel() = Saves a DataFrame as an Excel file (.xlsx).

df.to_excel( "students.xlsx", sheet_name="Students", index=False)      #Specify sheet name: Now the Excel workbook contains a sheet named:

In [2]:
# (50.)  to_dict() = Converts a DataFrame into a Python dictionary.

print(df.to_dict())

{'Names': {0: 'Ramesh', 1: 'Raghu', 2: 'Vikram'}, 'Age': {0: 22, 1: 21, 2: 19}}

In [3]:
print(df.to_dict(orient="records"))         #  This is especially useful when working with APIs and JSON-like data.

[{'Names': 'Ramesh', 'Age': 22}, {'Names': 'Raghu', 'Age': 21}, {'Names': 'Vikram', 'Age': 19}]

In [63]:
# (51.) to_html() = Converts a DataFrame into an HTML table.

html = df.to_html()
print(html)

# another way
with open("students.html", "w") as file:
    file.write(html)

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Student_ID</th>
      <th>Name</th>
      <th>Age</th>
      <th>Course</th>
      <th>Marks</th>
      <th>City</th>
      <th>Result</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>101</td>
      <td>Ramesh</td>
      <td>23</td>
      <td>Python</td>
      <td>92</td>
      <td>Hyderabad</td>
      <td>A+</td>
    </tr>
    <tr>
      <th>1</th>
      <td>102</td>
      <td>Priya</td>
      <td>21</td>
      <td>Java</td>
      <td>88</td>
      <td>Bangalore</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>2</th>
      <td>103</td>
      <td>Rahul</td>
      <td>24</td>
      <td>Data Science</td>
      <td>95</td>
      <td>Chennai</td>
      <td>A+</td>
    </tr>
    <tr>
      <th>3</th>
      <td>104</td>
      <td>Anjali</td>
      <td>22</td>
      <td>AI</td>
      <td>90</td>
      <td>Pune</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4</th>
      <td>105</td>
      <td>Kiran</td>
      <td>23</td>
      <td>Machine Learning</td>
      <td>85</td>
      <td>Mumbai</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>

In [64]:
# (52.) to_markdown() = Converts a DataFrame into a Markdown-formatted table.

print(df.to_markdown())

|    |   Student_ID | Name   |   Age | Course           |   Marks | City      | Result   |
|---:|-------------:|:-------|------:|:-----------------|--------:|:----------|:---------|
|  0 |          101 | Ramesh |    23 | Python           |      92 | Hyderabad | A+       |
|  1 |          102 | Priya  |    21 | Java             |      88 | Bangalore | nan      |
|  2 |          103 | Rahul  |    24 | Data Science     |      95 | Chennai   | A+       |
|  3 |          104 | Anjali |    22 | AI               |      90 | Pune      | nan      |
|  4 |          105 | Kiran  |    23 | Machine Learning |      85 | Mumbai    | nan      |